<?php if ($this->getCollection()->getSize()): ?>
<?php if ($this->getLastPageNum() > 1): ?>
<?php if (!$this->isLastPage()): ?>
    <a href="<?php echo $this->getNextPageUrl() ?>"><img alt="" src="<?php echo $this->getSkinUrl('images/archive/right_arc.jpg') ?>" width="19" height="40"></a>
<?php else : ?>
		<a><img alt="" src="<?php echo $this->getSkinUrl('images/archive/right_disable.jpg') ?>" width="19" height="41"></a>				
	<?php endif; ?>
<?php endif; ?>
<?php endif ?>
