<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-ENTERPRISE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento ENTERPRISE edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.1.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-ENTERPRISE.txt
 */
$tags_to_disp = (int) Mage::getStoreConfig(AW_Blog_Helper_Config::XML_TAGCLOUD_SIZE);

if ($tags_to_disp) {
?>
	<div class="tags">
        <span><?php echo Mage::helper('blog')->__('TAG:'); ?><span>

<?php
    $tags = explode(',', $this->getPost()->getTags());
    $tagCnt = 0;
    $total = count($tags);
    foreach ($tags as $tag):
        $tagCnt++;
        if ($tagCnt > $tags_to_disp) {
            break;
        }
?>
    <a href="<?php echo Mage::getUrl(Mage::helper('blog')->getRoute() . '/tag/' . urlencode($tag)) ?>"><?php echo $tag ?></a><?php echo $total == $tagCnt ? '' : ' '; ?>
<?php endforeach; ?>
	</div>
<?php
    }
?>