<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-ENTERPRISE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento ENTERPRISE edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.1.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-ENTERPRISE.txt
 */
?>

<?php if ($this->getCategories()->count()): ?>  
		<ul class="nav_menu">
			<?php $cats = $this->getCategories(); ?>
			<?php foreach ($cats as $cat): ?>
				<?php
					$currentUrl = Mage::helper('core/url')->getCurrentUrl();
					$cnt = substr_count($currentUrl, strtolower($cat->getTitle()));
					if ($cnt) {
						$activeClass = "class='blog_menu_active'";
					}else{
						$activeClass = "";
					}
				?>
				<li <?php echo $activeClass;?>><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle(); ?></a></li>
			<?php endforeach; ?>
		</ul>
<?php endif; ?>
