<?php
/**
 * Shopping cart product list
 *
 */
?>
<?php
	$_item = $this->getItem();
	$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
	$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td>
			<div class="proimg"><?php if ($this->hasProductUrl()):?><a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>"><?php endif;?><img src="<?php echo $this->getProductThumbnail()->resize(75); ?>" width="75" height="75" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /><?php if ($this->hasProductUrl()):?></a><?php endif;?></div>
			<div class="prodetail">
				 <?php if ($this->hasProductUrl()):?>
				<h3><a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()); ?></a></h3>
				<?php else: ?>
					<?php echo $this->htmlEscape($this->getProductName()); ?>
				<?php endif; ?>
				
				<?php if ($_options = $this->getOptionList()): $option_array = array();?>
				<?php foreach ($_options as $_option) :?>
				<?php $_formatedOptionValue = $this->getFormatedOptionValue($_option); ?>
				<?php 
					if($_option['label'] == 'Color')
						$option_array['color'] = $_formatedOptionValue['value'];
					 else if($_option['label'] == 'Size')
						$option_array['size'] = $_formatedOptionValue['value']; 
				?>
				<?php endforeach; ?>
				
				<p><?php 
					if(isset($option_array['size']) && isset($option_array['color'])) echo $option_array['size'].'/'.$option_array['color']; 
					else if(isset($option_array['size'])) echo $option_array['size'];
					else if(isset($option_array['color'])) echo $option_array['color'];
					?>
				<?php endif;?>
				<br/>
				Qty : <input name="cart[<?php echo $_item->getId() ?>][qty]" onchange="javascript:updatecart(this);" value="<?php echo $this->getQty() ?>" size="4" title="<?php echo $this->__('Qty') ?>" class="input-text qty" maxlength="12" /></p>
				<?php if ($messages = $this->getMessages()): ?>
				<?php foreach ($messages as $message): ?>
					<p class="item-msg <?php echo $message['type'] ?>">* <?php echo $this->escapeHtml($message['text']) ?></p>
				<?php endforeach; ?>
				<?php endif; ?>
				
				<?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
				<?php if ($addInfoBlock): ?>
					<?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
				<?php endif;?>
				
				<?php if ($isVisibleProduct): ?>
				<h4><a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo $this->__('Edit item parameters') ?>"><?php echo $this->__('Edit') ?></a></h4>        
				<?php endif ?>
			</div>
		</td>
		<td>
		<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
			<td class="a-center">
				<?php if ($isVisibleProduct): ?>
					<a href="<?php echo $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>" class="link-wishlist use-ajax"><?php echo $this->__('Move'); ?></a>
				<?php endif ?>
			</td>
		<?php endif ?>
		
		<?php if ($canApplyMsrp): ?>
			<td class="a-right"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif; ?>>
				<span class="cart-price">
					<span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
					<?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
					<a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__("What's this?"); ?></a>
					<script type="text/javascript">
						Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__("What's this?") ?>");
					</script>
				</span>
			</td>
		<?php else: ?>
        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="a-right">
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                <span class="cart-price">
				<?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                <?php else: ?>
                    <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()); ?>
                <?php endif; ?>
				</span>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <?php endif; ?>
        
        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>

			<h5>
            <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
            <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
                <?php else: ?>
                    <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
                <?php endif; ?>
                <u><?php echo $this->helper('checkout')->formatPrice($_item->getProduct()->getPrice())?></u>
				<br>
				<?php 
					$_finalPrice = $this->helper('checkout')->formatPrice($_item->getProduct()->getFinalPrice());
					$_price = (int)$this->helper('checkout')->formatPrice($_item->getProduct()->getPrice());
					$difference =$_item->getProduct()->getPrice() - $_item->getProduct()->getFinalPrice();
				?>
				<?php if($difference > 0): ?>
					<?php $_savePercent = round(($difference*100)/$_item->getProduct()->getPrice());?>
				<?php echo $_savePercent; ?>% OFF
				<?php endif; ?>
				
				<?php 
					if (Mage::helper('weee')->getApplied($_item)): 
				?>

                <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
                <?php 
					if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): 
                ?>
                    <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
                    </div>
                <?php  endif; ?>
                
            <?php endif; ?>
            
        <?php endif; ?>
    <?php endif; ?>
   
			</h5>
			<a href="<?php echo $this->getDeleteUrl()?>" title="<?php echo $this->__('Remove item')?>" class="removebut"><?php echo $this->__('Remove')?></a>
		</td>
	</tr>
	 <script type="text/javascript">decorateTable('shopping-cart-table')</script>
</table>
