<?php $_product = $this->getProduct(); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $pObj = Mage::getModel( 'catalog/product' )->load( $_product->getId() );
$catIds = $pObj->getCategoryIds();
$catId = in_array( $catIds[0], array( 3,4,5,6,8,7,256,260) ) ? $catIds[1] : $catIds[0];
$cats = Mage::getModel( 'catalog/category' )->load( $catId );
$_taxHelper  = Mage::helper('tax');
$_finalPrice = $_taxHelper->getPrice($_product, $_product->getFinalPrice());
$_price = $_taxHelper->getPrice($_product, $_product->getPrice());
$img_url = $this->helper('catalog/image')->init($_product, 'image')->resize('395' , '413');
Mage::getSingleton('core/session')->setRedirectURL($cats->getUrl());
$storeId = Mage::app()->getStore()->getId();
$summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)->load($_product->getId());
?>
<script type="text/javascript" src="<?php echo $this->getJsUrl('jquery/easyzoom.js'); ?>"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery(function(){jQuery("select").uniform();});
		jQuery(function(){jQuery('input[type="checkbox"]').uniform();});
        //jQuery(function(){jQuery("select").not("#currency_switcher").uniform();});
        
        // scroll on top
        //jQuery('html, body').animate({scrollTop: 220});
        <?php if($pObj->getTypeID() != 'giftcard'){ ?>
        //jQuery(window).scrollTop(220);
        <?php } ?>
    
    });
    
function addToCartByAjax(isRedirect) {
	if(isRedirect == "1") {
		document.getElementById("product_addtocart_form").submit();
	}
	else {
		var formData = jQuery('#product_addtocart_form').serializeArray();
		var saveData = jQuery.ajax({
			  type: 'POST',
			  url: "<?php echo $this->getBaseUrl(); ?>checkout/icart/add",
			  data: formData,
			  dataType: "text",
			  success: function(resultData) {
				  
				  jQuery.ajax({ 
					url: "<?php echo $this->getBaseUrl() ?>common/index/ajaxCartUpdate",
					cache: false,
					success: function(result){ jQuery('#my-bag-qty').html(result); jQuery('#my-bag-qty-mobile').html(result); } 
					});
		 	 
				  jQuery('#ajax-loading').hide();
				  jQuery('#bagholder').show();
				  jQuery('#bagholder-mobile').show();
				  setTimeout( "jQuery('#bagholder').hide();",10000 );
				  setTimeout( "jQuery('#bagholder-mobile').hide();",10000 );
				  //jQuery("#ajax-response").html(resultData);
				  //window.location="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>"; 
			  }
		});
		saveData.error(function() { jQuery("#ajax-response").html("Something went wrong"); });
	}
}    
</script>

<script type="text/javascript">
dataLayer.push(
    {'PRODUCT_ID': '<?php echo $_product->getSku() ?>'}, 
    {'PRODUCT_NAME': "<?php echo $_product->getName() ?>"},
    {'PRODUCT_IMG_URL': '<?php echo $img_url ?>'},
    {'PRODUCT_PRICE': '<?php echo $_finalPrice ?>'},
    {'PRODUCT_MRP': '<?php echo $_price ?>'},
    {'DEPT_ID': '<?php echo $cats->getParentCategory()->getId() ?>'}, 
    {'DEPT_NAME': "<?php echo $cats->getParentCategory()->getName() ?>"},
    {'CATEGORY_ID': '<?php echo $cats->getId() ?>'}, 
    {'CATEGORY_NAME': "<?php echo $cats->getName() ?>"},
    {'PAGE_TYPE': 'PRODUCT_VIEW'}
);
</script>
<?php
$flag = 0;
if (isset($_SERVER['REQUEST_URI'])) {
    $_tempVar = $_SERVER['REQUEST_URI'];
    if (strpos($_tempVar, "q=439ed537979d8e831561964dbbbd7413")) {
        $flag = 1;
    }
}
$dados = array();

	if(Mage::getStoreConfig('progallery/resizeImage/main_image_resize_width')) {
			$main_image_resize_width = Mage::getStoreConfig('progallery/resizeImage/main_image_resize_width');
		} else {
			$main_image_resize_width = 395;	
	}
	   
	if(Mage::getStoreConfig('progallery/resizeImage/main_image_resize_height')) {
			$main_image_resize_height = Mage::getStoreConfig('progallery/resizeImage/main_image_resize_height');
	} else {
			$main_image_resize_height = 413;	
	}
	   
if ($_product->getTypeId() == "configurable") {
    $associated_products = $_product->getTypeInstance()->getUsedProducts();
    foreach ($associated_products as $assoc) {
        $moreImg = array();
        $assocImg = Mage::getModel('catalog/product')->load($assoc->getId())->getMediaGalleryImages();
        $img = (string) $this->helper('catalog/image')->init($assoc, 'image', $assoc->image)->resize(
		$main_image_resize_width , $main_image_resize_height);
        foreach ($assocImg as $key => $value) {
            $moreImg[] = $value->getData();
        }
        $dados[$assoc->getId()]['main_image'] = $img;
        $dados[$assoc->getId()]['config_simple_product_id'] = $assoc->getId();
        $dados[$assoc->getId()]['more_image'] = $moreImg;
        unset($img);
        unset($moreImg);
    }
} else {
    $dados[] = "''";
}
$jsonString = json_encode($dados);
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    var assocIMG = <?php echo $jsonString; ?> // Added  - Removed { here, causes issues with other scripts when not working with a configurable product.
   
</script>
<div id="messages_product_detail_view"> 
<?php $msg = $this->getMessagesBlock()->toHtml();
$msg = str_replace('Rs. ', '<span class="WebRupee">Rs. </span>', $msg);
echo $msg; ?>
</div>
<div id="ajax-response"></div>
<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
       <?php if ($_product->getTypeId() == "giftcard") { ?>
		<div class="Product-Detail">
		<?php  echo $this->getChildHtml('product_type_data'); ?>
<?php } else {?>
<div class="Product-Detail" itemscope itemtype="http://schema.org/Product">
			<div class="LeftColumn">
			<!-- Social Icon start -->	
            <div class="sol-top-wrap">
            
				<!-- facebook share button start -->
				<div class="fb-top-count fl">
				<iframe src="//www.facebook.com/plugins/like.php?href=<?php echo $_product->getProductUrl(); ?>&width&layout=button_count&action=like&show_faces=false&share=true&height=21&appId=323522714412740" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;" allowTransparency="true"></iframe>
				</div>
				<!-- facebook share button end -->
				
				<!-- twitter count start -->
				<div class="twit-top-count fl">				
					<a class="twitter-share-button" href="https://twitter.com/share" data-url="<?php echo $_product->getProductUrl(); ?>" data-via="AmericanSwan">Tweet</a>
					<script type="text/javascript">
					window.twttr=(function(d,s,id){var t,js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return}js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);return window.twttr||(t={_e:[],ready:function(f){t._e.push(f)}})}(document,"script","twitter-wjs"));
					</script>
				</div>
				<!-- twitter count end -->
				
				<!-- pinterest start -->
				<div class="pint-counter fl">
					<a href="http://www.pinterest.com/pin/create/button/?url=<?php echo $_product->getProductUrl(); ?>&media=<?php echo $_product->getImageUrl(); ?>&description=<?php echo $_product->getDescription(); ?>"data-pin-do="buttonPin" data-pin-config="beside">
						<img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" />
					</a>
					<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>			
				</div>
				<!-- pinterest end -->
				
				<!-- facebook comment count start -->	
				<div class="cmt-counter-wrap fl">
					<div class="fb-comments-count" data-href="<?php echo $_product->getProductUrl(); ?>"></div>
				</div>
				<!-- facebook comment count end -->
            </div>
            
			 <script>           
			jQuery(document).ready(function(e) {
				
                jQuery('.product-img-box').mouseover(function(){ 
				    jQuery('.sol-top-wrap').show();
					
				}),jQuery('div.sol-top-wrap').mouseenter(function(){ 
				    jQuery('.sol-top-wrap').show();
					
				}),jQuery('.Product-Detail').mouseleave(function(){ 
				    jQuery('.sol-top-wrap').hide();
				});
			});
			 </script>
		<!-- Social Icon end -->	 
            	<div class="product-img-box">
					<?php echo $this->getChildHtml('media') ?>
				</div>
                
                <?php echo $this->getChildHtml('tabdata') ?>
                
			</div>	
    		<div class="pdp-r-panel fl">
				<h1 itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h1>
                 <div class="prd-code-info">Product Code: <?php echo $_product->getSku(); ?></div> 
        		<div class="clear"></div>
                <div class="pdp-price fl">
					<?php
					$aggregateRating = '';
					if($summaryData['rating_summary']) {
						$aggregateRating = ' itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating"';
					}
					?>                    
                    <div class="rating fl" <?php echo $aggregateRating; ?>>
					<?php if($summaryData['rating_summary']) { ?>							        
                        <meta itemprop="ratingValue" content="<?php echo ($summaryData['rating_summary']*5)/100; ?>"/>
                        <meta itemprop="ratingCount" content="<?php echo isset($summaryData['reviews_count'])?$summaryData['reviews_count']:0 ?>"/>
                    <?php } ?>    
					<?php echo $this->getReviewsSummaryHtml($_product, false, true) ?></div>
                    <div class="social_media">
						<?php echo $this->getLayout()->createBlock('sharingtool/share')->setTemplate('addthis/sharingtool/share.phtml')->_toHtml();?>
                    </div>
                </div>
                <div class="clear"></div>
				<div class="prd-ilst-wrap fl">
                <?php 
				
				echo $this->getChildHtml('customprice');  ?>
                
                <div class="clear"></div>
		 		
				<?php 
                if ($_product->isSaleable() && $this->hasOptions() && $this->getChildChildHtml('container2')):
				    
                        echo $this->getChildChildHtml('container2', '', true, true);	
					
                else:
                        echo $this->getChildHtml('product_options_wrapper');
                if (!$this->hasOptions()):		
                    if ($_product->isSaleable()):
                        echo $this->getChildHtml('addtocart');
                    endif;		
                    echo $this->getChildHtml('addto');
                else:		
                    if ($_product->isSaleable()):                
                ?>	
                    <div class="options-container-small">
                        <?php echo $this->getChildChildHtml('container1', '', true, true); ?>                        
                    </div>
					<?php
                    else :			
                        echo $this->getChildHtml('addto');			
                    endif; /* end of if ($_product->isSaleable()): */		
                    endif; /* end of if (!$this->hasOptions()): */
                    endif; /* if ($_product->isSaleable() && $this->hasOptions() */                
                ?>
                <?php if (!$_product->isSaleable()):?>
                	<div class="soldout-icon ">Sold Out </div><div class="clear"></div>
                <?php endif; ?>                
                <?php
                $product_style = $_product->getStyle();
                $collection = Mage::getModel('catalog/product')->getCollection();
                $collection->addAttributeToSelect('*');
                $collection->addFieldToFilter(array(array('attribute'=>'style','eq'=>$product_style)));
                $collection->addFieldToFilter(array(array('attribute'=>'visibility','neq'=>'1')));
                $collection->addFieldToFilter(array(array('attribute'=>'status','eq'=>'1')));
                $collection->getSelect()->limit(10);
                $group_products = array();
                if (count($collection) > 0):
                    foreach ($collection as $group_product):
                        $pSizes[$group_product->getData('entity_id')] = array();
                        if($group_product->getTypeId() == "configurable"):
                             $conf = Mage::getModel('catalog/product_type_configurable')->setProduct($group_product);
                             $simple_collection = $conf->getUsedProductCollection()->addAttributeToSelect('*')->addFilterByRequiredOptions();
                             foreach($simple_collection as $simple_product):
                                 $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($simple_product);
                                 if($stock->getQty() <= 0) continue;
                                 $pSizes[$group_product->getData('entity_id')][] = $simple_product->getAttributeText('size');
                             endforeach;
                             if (count($pSizes[$group_product->getData('entity_id')]) <= 0) {
                                 continue;
                             }
                             $group_products[] = $group_product;
                         endif;
                     endforeach;
                     if (count($group_products) > 0):
                ?>
                <div class="clear"></div>
                <?php if (count($group_products) > 1) : ?>
                <div class="color-pallet-wrap fl">
                <ul class="fl">
                <?php foreach ($group_products as $group_product):
                    if($flag == 1):
                        $_productUrl = $group_product->getProductUrl().'?sale=true';
                    else:
                        $_productUrl = $group_product->getProductUrl();
                    endif; ?>
                <li><a href="<?php echo $_productUrl ?>" class="<?php echo ($group_product->getData('entity_id') == $_product->getData('entity_id') ? "enable-color" : "") ?>"><img src="<?php echo $this->helper('catalog/image')->init($group_product, 'small_image')->resize(52,54); ?>" width="52" height="54" /></a></li>
                <?php endforeach;
		if (trim($_product->getData('display_color')) != ""):  ?>
                </ul>
                <div class="col-selc-wrap fl">Current Color<br /><?php echo $_product->getData('display_color') ?></div>
		<?php endif; ?>
                </div> 
                <?php endif; ?>
                <?php endif;
                endif; ?>
			</div>
        	<div class="Prod-desc-wrapp fl">
				<div class="prd-desc-maintxt"><h2>Product Description</h2></div>
				<span itemprop="description"><?php if(strlen($pObj->getData('description')) > 300) { echo substr($pObj->getData('description'), 0, 300).'...'; } else { echo nl2br($pObj->getData('description')); } ?></span>
			</div>

        	    <div class="clear"></div>
                <?php echo $this->getLayout()->createBlock('zipcodeimport/zipcodeimport')->setTemplate('zipcodeimport/cod.phtml')->_toHtml(); ?>
                <div class="clear"></div>
                <div class="free-s-exch-wrap">
                    <div class="free-ship-link-wrap"><a href="javascript:void(0);"><span class="fl"></span>FREE SHIPPING</a></div>
                    <div class="exchange-link-wrap"><a href="javascript:void(0);"><span class="fl"></span>14 DAYS FREE EXCHANGE</a></div>
                    <div class="info-free-ship">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('delivery-v2')->toHtml() ?>
                        <div class="pdpclose-btn"></div>
                    </div>
                    <div class="exchange-return">
                       <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('returns-v2')->toHtml() ?>
                        <div class="pdpclose-btn"></div>
                    </div>
                </div>
       	    <div class="clear"></div>
             <!-- facebook comment start -->
             <div id="fb-root">    
             <div class="fb-comments" data-href="<?php echo $_product->getProductUrl(); ?>" data-width="470" data-numposts="5" data-colorscheme="light"></div>
             </div>
             <!-- facebook comment end -->
			</div> 
        	<div class="clear"></div>
		</div>
    	<?php /*<div class="Bestsellers Best-Detail-page">
            <div id="tabsNew">
                <div class="Best-Tab">
                    <a class="tabNew active" href="javascript:void(0);" name="content_0_0">Recently Viewed</a>
                    <a class="tabNew" href="javascript:void(0);" name="content_1_0">Best Seller</a>
                    <a class="tabNew" href="javascript:void(0);" name="content_2_0">Customer Who bought also </a>
                </div>
                <div id="content_0_0" class="featuredContentNew">
                    <div id="recentlyViewed"></div>
                </div>
                <div id="content_1_0" class="featuredContentNew">
                <?php //echo $this->getChildHtml('sellers'); ?>
                </div>       
                <div id="content_2_0" class="featuredContentNew">
                    <?php //echo $this->getChildHtml('recommend') ?>
                </div>
                <div class="clear"></div>
            </div>
      	</div>
      	*/ ?> 
  <?php }?>
		<script type="text/javascript">
        jQuery(document).ready(function(){
			jQuery("a.tabNew").click(function() {
				// switch all tabs off
				jQuery("#tabsNew .active").removeClass("active");
				// switch this tab on
				jQuery(this).addClass("active");
				// hide all content
				jQuery(".featuredContentNew").hide();
				// show this content
				var content_showNew = jQuery(this).attr("name");
				jQuery("#"+content_showNew).show();
			});
        });
        </script>
<div class="itempanel">
<a name='pager'></a>
<div id="reviewbox" style="display:none">
<img src="<?php echo $this->getSkinUrl('images/loading_small.gif') ?>">
</div>
<div id="callreview"></div>
</div>
<?php echo $this->getChildHtml('popuphtml') ?>
<script type="text/javascript">
	jQuery("#review_frame_main, #review_frame_add_first, #review_frame_add").bind('click', function() {		
					
		jQuery.ajax({
					url:"<?php echo Mage::getBaseUrl(); ?>common/index/callReview/id/<?php echo $_product->getId(); ?>",
					beforeSend: function() {
							jQuery('#reviewbox').show();
					},
					success:function(result) {
						if(result) {
							jQuery('#reviewbox').hide();
							jQuery("#callreview").html(result);
						}
					
					}
			});			
		});
		
    //<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
                form.action = url;
            }
            var e = null;
            try {
                jQuery("#amsloader").show();
                this.form.submit();
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
    //]]>
</script>
<script type="text/javascript">
// &lt;![CDATA[
jQuery(document).ready(function(e) {
jQuery('.free-ship-link-wrap, .exchange-link-wrap').click(function(){
jQuery('.info-free-ship, .exchange-return').show();
}),jQuery('.info-free-ship').click(function(){
jQuery('.info-free-ship, .exchange-return').hide();

}),jQuery('.exchange-link-wrap, .pdpclose-btn').click(function(){
jQuery('.info-free-ship').hide();
}),jQuery('.free-ship-link-wrap, .pdpclose-btn').click(function(){
jQuery('.exchange-return').hide();

}),jQuery('.exchange-link-wrap').mouseover(function(){
jQuery('.info-free-ship').hide();
}),jQuery('.free-ship-link-wrap').mouseover(function(){
jQuery('.exchange-return').hide();

}),document.onkeydown = function(evt) {
evt = evt || window.event;
if (evt.keyCode == 27) {
//alert("Escape");
jQuery('.info-free-ship, .exchange-return').hide();
}
};

});
// ]]&gt;
</script>
</form>
<?php
$sid_peram = Mage::app()->getRequest()->getParam('sid', false);
        $sesId = isset($_COOKIE['adminhtml']) ? $_COOKIE['adminhtml'] : false ;
        if($sid_peram != "" && $sid_peram == $sesId) :
?>
<div style="position: fixed; top: 0px; left: 0px; width: 158px; height: 194px; background-color: lightyellow; z-index: 9999999999999999;">
    <div style="background-color: darkkhaki; font-weight: bold; padding: 5px;">Admin Action</div>
    <div style="padding: 5px; font-weight: bold; border: 1px solid darkkhaki; border-top: none; height: 156px;">
        <form action="<?php echo $this->getUrl() ?>catalog/product/updateqc/id/<?php echo $_product->getId() ?>/sid/<?php echo $sid_peram ?>" action="post" >
            ● Product is <?php echo (($_product->getData('status') == 1) ? 'Enabled' : 'Disabled'); ?><br/>
            ● QC <?php echo (($_product->getData('qc_ok') == 1) ? 'Passed' : (($_product->getData('qc_ok') == 2) ? 'Failed' : 'Pending')); ?>
            <br/><br />
            <input type="checkbox" name="status" id="status" value="1" <?php echo (($_product->getData('status') == 1) ? 'checked="checked"' : ''); ?> />Enable<br>
            <div id="controls">
                <button name="qc_status" value="1" onclick="jQuery('#controls').hide(); jQuery('#please_wait').show(); this.submit();" style="background-color: green; width: 146px;">QC Pass</button><br/>
            <button name="qc_status" value="2" onclick="jQuery('#controls').hide(); jQuery('#please_wait').show(); jQuery('#status').attr('checked', false); this.submit();" style="background-color: red; width: 146px;">QC Fail</button>
            </div>
            <div id="please_wait" style="background-color: lightcyan; height: 45px; border: 1px solid; color: red; display: none; font-weight: normal; padding: 19px; text-align: center;">Please wait<br/>while updating...</div>
        </form>
    </div>
</div>
<?php endif; ?>
