<?php if ($this->displayBoth()):?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->helper('tax')->__('Subtotal (Excl. Tax)') ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueExclTax()) ?>
    </td>
</tr>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->helper('tax')->__('Subtotal (Incl. Tax)') ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueInclTax()) ?>
    </td>
</tr>
<?php else : ?>
<tr>
    <td><?php echo $this->helper('tax')->__('Items');?></td>
    <td><?php echo Mage::getModel('checkout/cart')->getQuote()->getItemsQty(); ?>
    
    </td>
</tr>
<tr>
    <td><?php echo $this->helper('tax')->__('Sub Total ( Incl. of Tax )');?></td>
      
    <td><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()); ?></td>
</tr>
<?php endif;?>
