<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 * @var $this Mage_Checkout_Block_Cart_Totals
 */
?>
<?php if ($this->canApplyMsrp()): ?>
    <div class="cart-msrp-totals"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></div>
<?php else: ?>
    <table id="shopping-cart-totals-table" width="100%" border="0" cellspacing="0" cellpadding="0">
        <col />
        <col width="1" />
        <tfoot>
            <?php echo $this->renderTotals('footer'); ?>
        </tfoot>
            <?php echo $this->renderTotals(); ?>
    </table>
<?php endif; ?>
