<?php
$newarrival_id =  $this->getRequest()->getParam('id');
$getData = Mage::getModel('newarrival/managenewarrival')->getNewArrivalMenWomenById($newarrival_id);
?>        
<div class="" id="anchor-content">
<div id="page:main-container">
<div class="main-col" id="content" style="margin-left:0px !important;" >
<div class="main-col-inner">
<div id="messages"></div>
<div class="content-header">
<h3 class="icon-head head-adminhtml-zipcodeimport">Manage New Arrival</h3>
<p class="form-buttons"><button  onclick="submitform();" title="Save Categories" type="button" class="scalable save" style=""><span><span><span>Save</span></span></span></button></p>
<p class="form-buttons"><button  onclick="redirect();" title="Save Ctegories" type="button" class="scalable save" style=""><span><span><span>Back</span></span></span></button></p>
</div>
<div class="entry-edit">
<form  name="myform" id="myform" method="POST" action="<?php echo $this->getBaseUrl();?>newarrival/adminhtml_index/add/id/<?php echo $newarrival_id;?>">
<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">New Arrival</h4>
		<div class="form-buttons"></div>
	</div>
	<div class="fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
						<td class="label"><label>Select Option<span class="required">*</span></label></td>
						<td class="value">
							<select id="is_default" name="is_default" class="required-entry required-entry select"/>										
								<option value="1" <?php if ($getData[0]['is_default'] == '1' ) echo 'selected="selected"'; ?>>Default</option>
								<option value="0" <?php if ($getData[0]['is_default'] == '0' ) echo 'selected="selected"'; ?>>Custom</option>
							</select>             
						</td>
					</tr>
					<tr id="custom_cat_row">
						<td class="label"><label>Category<span class="required">*</span></label></td>
						<td class="value">
							<select id="cat_id" name="cat_id" class="required-entry required-entry select">										
								<option value="">Select Category</option>
								<option value="6" <?php if ($getData[0]['cat_id'] == 6 ) echo 'selected="selected"'; ?>>Men</option>
								<option value="8" <?php if ($getData[0]['cat_id'] == 8 ) echo 'selected="selected"'; ?>>Women</option>
							</select>             
						</td>
					</tr>
					<tr id="custom_sku_row" <?php echo ($getData[0]['is_default'] == '0' ) ? '' :' style="display:none;"' ?>>
						<td class="label"><label>SKU<span class="required">*</span></label></td>
						<td class="value">
							<input id="sku" name="sku" type="text" class="input-text required-entry" value="<?php echo $getData[0]['sku'];?>">           
						</td>
					</tr>			
					<tr>
						<td class="label"><label><span class="required"></span></label></td>
						<td class="value"> 
							<button title="Save New Arrival" onclick="submitform();" type="button" class="scalable save" style=""><span><span><span>Save</span></span></span></button>
						</td>
					</tr>	
				</tbody>
			</table>
		</div>
	</div>
</div>
</form>
</div>
</div>
</div>
</div>
</div>
<script>
	jQuery("#is_default").change(function() { 
    if (jQuery(this).val() == "0") {
		jQuery("#custom_sku_row").hide();
		jQuery("#custom_sku_row").show();
	}
    else{
        jQuery("#custom_sku_row").show();
        jQuery("#custom_sku_row").hide();
	}
	});
</script>
<script type="text/javascript">
	
	function redirect()
	{
		window.location.href="<?php echo $this->getBaseUrl();?>newarrival/adminhtml_index/";
	}
	
	function submitform()
	{
		var validate = formValidate();	
		if(validate)
		document.forms["myform"].submit();
	}
	
	function formValidate(){
		
		jQuery('.remove').remove();
		var message 	= '<span style="color:red;" class="remove">This field is required.</span>';
		var cat_id 		= jQuery('#cat_id').val();
		var sku 		= jQuery('#sku').val();
		var is_default 		= jQuery('#is_default').val();
		if((cat_id.length === 0 || cat_id === null)) {
			jQuery('#cat_id').parent().append(message);
			return false;
		}
		else if(is_default == '0' && ( sku.length === 0 || sku === null)) {
			jQuery('#sku').parent().append(message);
			return false;
		}
		else {
			return true;
		}
	}
</script>
