<?php
/**
 * Product:     Layered Navigation Pro for Enterprise Edition - 16/08/12
 * Package:     AdjustWare_Nav_10.4.9_10.0.0_557110
 * Purchase ID: hXgQU3oI8FOfJ8PDCk5s6h6XPM5oH2Kx0N6TCAPkqN
 * Generated:   2013-04-22 06:59:44
 * File path:   app/design/frontend/enterprise/default/template/adjnav/filter_category_search.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<?php $_helper = Mage::helper('catalog/category'); ?>
<?php $_categories = $_helper->getStoreCategories(); ?>
<?php if (count($_categories) > 0): ?>
        <?php foreach($_categories as $_category): ?>
            <?php $catArray[] = $_category->getId(); ?>
        <?php endforeach; ?>
			<?php $catArray[] = 2; ?>
<?php endif; ?>
<div class="left-links" style="margin-top:0px;">
<p class="cat-heading"><?php  echo 'shop by categories'; ?></p>
<ul>
<?php
foreach ($this->getItems() as $_item):?>
<?php
      	$excludeLink = array("get the look","new arrivals","collections","sale","valentine gift","men","women");
		if(in_array(strtolower(trim($_item->getLabel())),$excludeLink))
		{
		    continue;
		}
    ?>
	<?php $_flag = 0; ?>
		<?php $_itemCatId = $_item->getValue(); ?>
		<?php if($_itemCatId != ''): ?>
			<?php if(in_array($_itemCatId,$catArray)): ?>
				<?php $_flag = 1; ?>
			<?php endif; ?>
		<?php else: ?>
			<?php $param = $_GET['cat']; ?>
				<?php if(in_array($param,$catArray)): ?>
					<?php $_flag = 1; ?>
				<?php endif; ?>
		<?php endif; ?>
    <li>
        <?php if ($_item->getIsCurrent()): ?>
            <a class="adj-nav-category-current active" href="javascript:void(0);"><?php echo $_item->getLabel() ?></a>
        <?php  else: ?>        
		<?php
		if (Mage::getStoreConfig('design/adjnav/reload_categories'))
		{
		?>
            <a id="cat-<?php echo $_item->getValue()?>" href="?dir=desc&p=clear&q=<?php echo isset($_GET['q']) ? $this->htmlEscape($_GET['q']) : ''?>&cat=<?php echo $_item->getValue()?>" class="adj-nav-pad<?php echo $_item->getLevel()?>"><?php echo $_item->getLabel() ?></a>			
		<?php } else { ?>
			<a onclick="return false;" id="cat-<?php echo $_item->getValue()?>" href="<?php echo $this->htmlEscape($_item->getUri()) ?>" class="adj-nav-category adj-nav-pad<?php echo $_item->getLevel()?>"><?php echo $_item->getLabel() ?></a>		
		<?php
		} ?>
        <?php endif ?>
    </li>
<?php endforeach ?>
</ul>
</div>
<div class="clear"></div>
