<?php
/**
 * Product:     Layered Navigation Pro for Enterprise Edition - 16/08/12
 * Package:     AdjustWare_Nav_10.4.9_10.0.0_557110
 * Purchase ID: hXgQU3oI8FOfJ8PDCk5s6h6XPM5oH2Kx0N6TCAPkqN
 * Generated:   2013-04-22 06:59:44
 * File path:   app/design/frontend/enterprise/default/template/adjnav/filter_price_default.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<ol>
<?php foreach ($this->getItems() as $_item): ?>
    <li class="<?php echo $this->getFeaturedItemStyle($_key) ?>">
        <a id="<?php echo $_item->getFilter()->getRequestVar() . '-' . $_item->getValueString()?>" 
           onclick="return false;" href="<?php echo $this->getItemUrl($_item); ?>" 
           class="adj-nav-price <?php if ($this->isSelected($_item)) echo 'adj-nav-price-selected';?>" >
               <?php echo $_item->getLabel() ?></a> 
               <?php if(0): ?>(<?php echo ($_item->getCount()>=0?$_item->getCount():$this->getCollectionSize()) ?>)<?php endif; ?>
    </li>
<?php endforeach ?>
</ol>