<?php
/**
 * Product:     Layered Navigation Pro for Enterprise Edition - 16/08/12
 * Package:     AdjustWare_Nav_10.4.9_10.0.0_557110
 * Purchase ID: hXgQU3oI8FOfJ8PDCk5s6h6XPM5oH2Kx0N6TCAPkqN
 * Generated:   2013-04-22 06:59:44
 * File path:   app/design/frontend/enterprise/default/template/adjnav/product_list_toolbar.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<?php $this->getPagerHtml(); ?>
<div class="toolbar">
    <?php if($this->getLastPageNum()>1): ?>
        <input type="hidden" class="adjnav-page-autoload-nextpage" value="<?php echo ($this->getCurrentPage() + 1) ?>"/>
    <?php endif; ?>
    <?php if( $this->isExpanded() ): ?>
    <div class="">
        <?php if( $this->isEnabledViewSwitcher() ): ?>
        <p class="view-mode">
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>
            <label><?php echo $this->__('View as') ?>:</label>
            <?php $_i=1; $_fix=''; foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if ($_i==1 && strtolower($_code)=='list') $_fix='-fix'; ?>
                <?php if($this->isModeActive($_code)): ?>
                    <strong class="<?php echo strtolower($_code); echo $_fix; ?>" title="<?php echo $_label ?>"><?php echo $_label ?></strong>
                <?php else: ?>
                    <a class="<?php echo strtolower($_code); echo $_fix; ?>" title="<?php echo $_label ?>" href="<?php echo $this->getModeUrl($_code) ?>"><?php echo $_label ?></a>
                <?php endif; ?>
            <?php $_i++; endforeach; ?>
            <?php endif; ?>
        </p>    
        <?php endif; ?>
    	<?php if(Mage::registry('current_category')) {
            $catImgUrl = '';
            $catImgUrl = Mage::registry('current_category')->getImageUrl();
            if($catImgUrl != '')
                $style = "style='margin-top: -30px;width: 150px;padding:2px 4px;'";
            else
                $style = "style='margin-top:-60px;width: 150px;padding:2px 4px;'";
        }else {
            $style = '';
        }
        ?>
        <div class="sort-oprion">
         <ul>
         <label>Sort:</label>
         <li onclick='adj_nav_toolbar_make_request("<?php echo $this->getOrderUrl('updated_at', 'desc') ?>");'>New Arrival</li>
         <li>|</li>
         <label>Discount</label>
         <li onclick='adj_nav_toolbar_make_request("<?php echo $this->getOrderUrl('discount', 'asc') ?>");'>Low</li>
         <li onclick='adj_nav_toolbar_make_request("<?php echo $this->getOrderUrl('discount', 'desc') ?>");'>High</li>
         <li>|</li>
         <label>Price:</label>
         <li onclick='adj_nav_toolbar_make_request("<?php echo $this->getOrderUrl('price', 'asc') ?>");'>Low</li>
         <li onclick='adj_nav_toolbar_make_request("<?php echo $this->getOrderUrl('price', 'desc') ?>");'>High</li>
         </ul>        
         </div>         
    <?php endif; ?>
    <div class="CatTitleLeft">
         <p><?php echo $this->__($this->getTotalNum()) ?> Products Found</p>
     </div>
     </div>
</div>
<?php endif ?>