<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>
<div class="quickslide">
    <?php if (count($this->getGalleryImages()) > 0): ?>
    <ul class="bxslider">
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
         <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(58, 61); ?>" data-larger="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
     </li>
    <?php endforeach; ?>        
    </ul>
    <?php endif; ?>     
</div>

<div class="mainimage">
<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(335, 350); ?>" /> 	
 </div>
	
<?php 
$countgal = count($this->getGalleryImages());
$GLOBALS['images_count'] = $countgal;
$has_after_paging = Mage::getStoreConfig('progallery/progalleryconfig/has_after_pagination');
if (Mage::getStoreConfig('progallery/thumbscarouselconfig/scrollitems')):
	$items = Mage::getStoreConfig('progallery/thumbscarouselconfig/scrollitems');
else:
	$items = '1';
endif;
if (Mage::getStoreConfig('progallery/thumbscarouselconfig/has_prevandnext')):
if ($countgal > $has_after_paging): 
?>
<?php 
endif;
endif;
?>