<?php $catalogSearchHelper =  $this->helper('catalogsearch'); 
$controName = Mage::app()->getRequest()->getControllerName();
$_utmparam = Mage::app()->getRequest()->getParam('utm_source');
$routeName = Mage::app()->getFrontController()->getRequest()->getRouteName();
$identifier = Mage::getSingleton('cms/page')->getIdentifier();
?>
<form name="search_mini_form" id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>"  method="get">
	<?php  $searchParam = '';
		$p = $catalogSearchHelper->getQueryParamName();
		if (isset($_GET[$p])) {	$searchParam = $_GET[$p]; }		
		if ($searchParam == '439ed537979d8e831561964dbbbd7413') { $searchParam = ''; }	
	?>
	<input name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" type="text" id="search" value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" onclick="this.value=='<?php echo $this->__('Search') ?>'?this.value='':''" onblur="this.value==''?this.value='<?php echo $this->__('Search American Swan') ?>':''" class="search rounded input-text required-entry" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>"/>&nbsp;	
	<input title="<?php echo $this->__('Search') ?>" class="search_btn_new go" type="submit">
    <div id="search_autocomplete" class=""></div> 
    <script language="javascript">
    //<![CDATA[
        var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search American Swan') ?>');
        searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
    //]]>
    </script>

</form>
<?php
$request = $this->getRequest();
$module = $request->getModuleName();
$controller = $request->getControllerName();
$action = $request->getActionName();
if (!($module == 'checkout' && $controller == 'onepage' && ($action == 'success' ||  $action == 'success-ccavenue'  ||  $action == 'success-citrus'  ||  $action == 'success-payseal'  ||  $action == 'success-zaakpay'))){
?>
<div style="position:absolute">
<!-- Advertiser 'Ignitee Digital Services Pvt Ltd.-THE AMERICAN SWAN LIFESTYLE COMPANY PVT LTD',  Include user in segment '1544425_THE AMERICAN SWAN LIFESTYLE COMPANY_SRT_Pixel_042913' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->
<img src="http://ad.yieldmanager.com/pixel?id=2366136&t=2" width="1" height="1" />
<!-- End of segment tag -->
</div>
<?php } ?>
<script type="text/javascript">
jQuery(window).bind("load", function() {
<?php if($controName != 'cart' && $routeName != 'checkout') { ?>
	<!-- Mydala pixel Start -->
	<?php if($_utmparam != ""): ?>
		jQuery.ajax({
			url:"<?php echo Mage::getBaseUrl(); ?>common/index/myDalaPixel",
			type: "post",
			data: { paramname: "<?php echo $_utmparam; ?>"},
			beforeSend: function() {
			},
			success:function(result){
				if(result != '0'){
					jQuery("#mydalapixel").show();
					jQuery("#mydalapixel").html(result);
				}
			}
		});
	<?php endif; ?>
	<!-- Mydala pixel End -->
<?php } ?>
});
</script>