
<?php
$step_counter = 1;
$helper = Mage::helper('onestepcheckout/checkout');

/* check to test if customer is logged in to skip the login - tab */
$_iscustomerLogedIn = false;
if($this->isCustomerLoggedIn()){
	$_iscustomerLogedIn = true;
}

$shipping_passed = $helper->checkShippingPassed();
$itemArr = Mage::helper('common')->getItemByType();
?>
<div id="amsloader" style="display:none;" class="giftCardloader">
	<div class="giftCardconf-Boxloader">
		<span style="text-align:center;" class="fl"><img src="<?php echo $this->getSkinUrl('images-v3/adj-nav-progress-v1.gif') ?>"></span>
	</div>
</div>

<div id="amsloader-2" style="display:none;" class="giftCardloader">
	<div class="giftCardconf-Boxloader">
		<span style="text-align:center;" class="fl"><img src="<?php echo $this->getSkinUrl('images-v3/adj-nav-progress-v1.gif') ?>"></span>
	</div>
</div>

<div class="ckcartleft-wrapp fl" id="checkout">
    <?php 
		$msg = $this->getMessagesBlock()->getGroupedHtml();
		echo str_replace('Rs. ', '<span class="WebRupee">` </span>', $msg);
	?>
		<span class="ck-cartleft-text fl fs18">checkout</span>
		<div class="clear"></div>

	<?php if(!$this->canCheckout() || !$this->validateMinimumAmount()): ?>
    <?php if($this->settings['checkout_title']): ?>
        <h1 class="onestepcheckout-title page_title"><?php echo $this->settings['checkout_title']; ?></h1>
    <?php endif; ?>

    <?php if($this->canCheckout() && !$this->validateMinimumAmount()): ?>
    <p><?php echo Mage::getStoreConfig('sales/minimum_order/description'); ?></p>
    <p><a href="<?php echo $this->getUrl(''); ?>"><?php echo $this->__('Back to homepage'); ?></a></p>
    <?php else: ?>
    <p><?php echo $this->__('You need to have products in your cart to checkout, and your cart is empty.'); ?></p>
    <p><a href="<?php echo $this->getUrl(''); ?>"><?php echo $this->__('Back to homepage'); ?></a></p>
    <?php endif; ?>
<?php else: ?>

    <div class="ckcartTab-cont f-lato" id="checkout_tab">
		<?php if(isset($this->formErrors['unknown_source_error'])): ?>
		<div class="onestepcheckout-error">
			<?php echo $this->formErrors['unknown_source_error']; ?>
		</div>
		<?php endif; ?>

		<div id="tabs-new" class="ckcartTab-wrapp sidebar">
			<ul class="sidebar">
			<?php if($_iscustomerLogedIn): ?>	
			  <li><a href="javascript:void(0)" id="paystp1" name="content_1" rel="1" class="tab one disabled"> <span id="checkout-signin" class="ck-signIn-ac"></span>Sign In </a> </li>
			  <li><a href="javascript:void(0)" id="paystp2" name="content_2" rel="2" class="tab two active"> <span id="checkout-delivery" class="ck-delivery-ac"></span>delivery </a> </li>
			  <li><a href="javascript:void(0)" id="paystp3" name="content_3" rel="3" class="tab three disabled ck-pay-tabfw"> <span id="checkout-payment" class="ck-payment"></span>payment </a> </li>
			<?php else: ?>
			  <li><a href="javascript:void(0)" id="paystp1" name="content_1" rel="1" class="tab one active"> <span id="checkout-signin" class="ck-signIn-ac"></span>Sign In </a> </li>
			  <li><a href="javascript:void(0)" id="paystp2" name="content_2" rel="2" class="tab two disabled"> <span id="checkout-delivery" class="ck-delivery"></span>delivery </a> </li>
			  <li><a href="javascript:void(0)" id="paystp3" name="content_3" rel="3" class="tab three disabled ck-pay-tabfw"> <span id="checkout-payment" class="ck-payment"></span>payment </a> </li>
		<?php endif; ?>	    
			</ul>
		</div>
		
		<div class="ckpay-cont-area contentarea fl" id="response1">
			<div id="content_1" class="ckcontent-main">
			   <?php echo $this->getChildHtml('loginpage'); ?>
			</div>
            <input type="hidden" class="shipping-tab-passed" name="shippingtabpassed" value="<?php echo $shipping_passed; ?>" />
            
            <form id="onestepcheckout-form" method="post" action="<?php echo $this->getUrl('onestepcheckout', array('_secure'=>true)); ?>">
                    <input id="time_slot_hiddenvalue" name="time_slot_hiddenvalue" type="hidden" value="" />
                    <!--Shipping Details content start here --->
                    <div id="content_2" class="ckcontent-main" style="display:none">                                                                        
				<div class="ckprd-shipdet-wrapp">
				<script type="text/javascript">var shipping = new Shipping();</script>
					<div class="fl content-tab" id="shipping_address">
						<div class="ckdeliv-txt-inner fs18 c-pantone" id="delivery-address">Delivery Address</div>
							<?php if ($this->customerHasAddresses()): ?>
								<div class="fr ckadd-ship-add-link fs18 c-pantone pos-r" id="add-new-address"> +ADD NEW ADDRESS</div>
								<div class="fr ckadd-ship-add-link fs18 c-pantone pos-r" id="list-of-addresses" style="display:none;">BACK TO SAVED ADDRESS</div>
								<div id="list-shipping-address">									
									<div class="clear"></div>									
									<?php 
									$addressArr = $this->getCustomerAddresses();
									$defaultChecked = isset($addressArr[0]['value']) ? $addressArr[0]['value'] : false;
									foreach($addressArr as $key=>$addressData){
										$addressText = "{$addressData['data']['firstname']} {$addressData['data']['lastname']}~{$addressData['data']['telephone']}~{$addressData['street1']}~{$addressData['street2']}~{$addressData['data']['postcode']}~{$addressData['data']['city']}~{$addressData['data']['region']}~{$addressData['data']['country_id']}";
									?>
									<div class="ckship-add-wrapp">
									<div class="ckprd-ship-exAddress fl fs13">
									<label>
									<input <?php echo ($defaultChecked == $addressData['value'] ? 'checked="checked"' : ''); ?> type="radio" id="shipping-address-select-<?php echo $addressData['value']; ?>" id="radio4" class="css-checkbox fl mar-r10" value="<?php echo $addressData['value']; ?>" name="ship" onclick="chooseShipping(this.value);" />
									  <p class="pl15"><?php echo $addressData['label'].', <strong>Mob:</strong> +91 '.$addressData['data']['telephone']; ?></p>
									  
									</label>	
									  <p class="ck-add-remove pad-r10 fr"> <?php /*<a class="ckshop-bag-text1 fl" href="javascript:void(0);" onclick="editShippingAddress(<?php echo $addressData['value']; ?>);">edit</a>*/?> <a class="ckremove-btn-new fl" href="javascript:void(0);" onclick="deleteShippingAddress(<?php echo $addressData['value']; ?>);">Remove</a></p>
									  <span style="display:none;" id="shipping_address_text_<?php echo $addressData['value']; ?>"><?php echo $addressText; ?></span>
									</div>									
									<div id="cart-loader-<?php echo $addressData['value']; ?>" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>"></div>
								  </div>
								  <?php } ?>
								  <input type="hidden" id="shipping-address-select" name="shipping_address_id" value="<?php echo $defaultChecked; ?>">
								  <input type="hidden" id="tmp_shipping_address_id" value="<?php echo $defaultChecked; ?>">
								  <input type="hidden" name="shipping[save_in_address_book]" class="shipping_save_address" value="0" />
								</div>
								<div class="clear"></div>
								<?php /*<div class="input-box"><?php echo $this->getAddressesHtmlSelect('shipping') ?></div>*/ ?>
							<?php endif ?>

							<div id="shipping_address_list" <?php if($this->customerHasAddresses() && !$this->getNewAddressSelectValueOnError('shipping')) { echo '  style="display: none;" '; } ?>>
							   <?php echo $this->getChildHtml('shipping_address');?>
								<?php $addressAttributes = $this->getChild('customer_form_shipping_address_user_defined_attributes');?>
								<?php if ($addressAttributes): ?>
									<?php $addressAttributes->setEntity($this->getQuote()->getShippingAddress())->setEntityType('customer_address');?>
									<?php $addressAttributes->setFieldIdFormat('shipping:%1$s')->setFieldNameFormat('shipping[%1$s]');?>
									<?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
								<?php endif;?>
								<input type="hidden" name="shipping[address_id]" value="<?php echo $this->getQuote()->getShippingAddress()->getId() ?>" id="shipping:address_id" />
							</div>
                            <!-- Billing Address -->
							<div class="mar-t30"> <span class="ckdeliv-txt-inner fs18 ckprd-l-color">Billing Address </span> </div>
							<div class="mar-b10 mar-t10 ckprd-l-color">
								<label>
								  <input class="fl" type="checkbox" name="shipping[use_for_billing]" id="shipping:use_for_billing_yes" value="1" <?php echo $this->isUseShippingAddressForBilling() == 1 ? "checked='checked'" : "" ; ?> />
								  <span class="ckprd-shipdet-txt fl fs18 ">Same as Delivery Address</span> 
								</label>
							</div>
							<div class="clear"></div>
							<div class="bill-add-sec">
								<div id="billing_address" class="billing_address">
                                    <script type="text/javascript">var billing = new Billing();</script>
                                    <?php if ($this->customerHasAddresses()): ?>
                                        <?php /*<div class="input-box"><?php echo $this->getAddressesHtmlSelect('billing') ?></div>*/?>
                                        
                                        <?php if(isset($this->formErrors['billing_error']) && count($this->formErrors['billing_errors']) > 0): ?>                                            
                                            <div class="onestepcheckout-error">
                                                <?php echo $this->__('Please check red fields below and try again.'); ?>
                                            </div>                                            
                                        <?php endif; ?>                                        
                                    <?php endif; ?>

                                    <div id="billing_address_list" <?php echo (($this->customerHasAddresses() && !$this->getNewAddressSelectValueOnError('billing')) ? 'style = "display:none"' : false ); ?>>
                                        <?php $prefix = $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]') ?>
                                        
                                        <?php echo $this->getChildHtml('billing_address');?>
                                        <?php $addressAttributes = $this->getChild('customer_form_billing_address_user_defined_attributes');?>
                                        <?php if ($addressAttributes): ?>
                                            <?php $addressAttributes->setEntity($this->getQuote()->getBillingAddress())->setEntityType('customer_address');?>
                                            <?php $addressAttributes->setFieldIdFormat('billing:%1$s')->setFieldNameFormat('billing[%1$s]');?>
                                            <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
                                        <?php endif;?>
                                        <?php $customerAttributes = $this->getChild('customer_form_customer_user_defined_attributes');?>
                                        <?php if ($customerAttributes): ?>
                                            <?php $customerAttributes->setEntityModelClass('customer/customer')->setFieldIdFormat('billing:%1$s');?>
                                            <?php $customerAttributes->setFieldNameFormat('billing[%1$s]')->setShowContainer(false);?>
                                            <?php echo $customerAttributes->setExcludeFileAttributes(true)->toHtml()?>
                                        <?php endif;?>
                                    </div>
                                </div>
                                </div>
							<!-- Billing Address -->
                                        
						</div>
                                
                            <?php if(!$this->isVirtual()): ?>
                                    <?php if(Mage::getStoreConfig('onestepcheckout/general/hide_shipping_method')):?>
                                        <?php if(isset($this->formErrors['shipping_method']) && $this->formErrors['shipping_method']): ?>
                                            <div class="onestepcheckout-error onestepcheckout-shipment-method-error">
                                                <?php echo $this->__('Please choose a shipping method.'); ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php echo $this->getChildHtml('choose-shipping-method'); ?>
                                    <?php else:?>
                                            <?php if(isset($this->formErrors['shipping_method']) && $this->formErrors['shipping_method']): ?>
                                            <div class="onestepcheckout-error onestepcheckout-shipment-method-error">
                                                <?php echo $this->__('Please choose a shipping method.'); ?>
                                            </div>
                                            <?php endif; ?>

                                            <div class="onestepcheckout-shipping-method-block shipping_method">
                                                <?php echo $this->getChildHtml('choose-shipping-method'); ?>
                                            </div>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <div class="clear"></div>
								<?php if(in_array('giftcard', $itemArr) && (in_array('configurable', $itemArr) || in_array('simple', $itemArr) )) { ?>
									<button type="button" class="ckcontinue-btn" onClick="javascript:orderNow();">CONTINUE</button>
								<?php }else{ ?>	
								<button type="button" id="checkout-delivery-add-continue" class="ckcontinue-btn gtm-track" onClick="javascript:validateShippingTab();">CONTINUE</button>
								<?php } ?>
					<div id="delivery-loader" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>"></div>				
                    </div>
                    </div>
                    <!-- payment options start --->
                    <div id="content_3" class="ckcontent-main" style="display:none">
                        <?php if(Mage::getStoreConfig('onestepcheckout/general/hide_payment_method')):?>
                            <?php if(!empty($this->formErrors['payment_method'])): ?>
                                <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                                    <?php echo $this->__('Please choose a payment method.'); ?>
                                </div>
                            <?php endif; ?>
                            <?php if(!empty($this->formErrors['payment_method_error'])): ?>
                                <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                                    <?php echo $this->__('Please enter valid details below.'); ?>
                                </div>
                            <?php endif; ?>
                            <?php echo $this->getChildHtml('choose-payment-method'); ?>
                      <?php else: ?>
                        <?php if(isset($this->formErrors['payment_method']) && $this->formErrors['payment_method']): ?>
                            <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                            <?php echo $this->__('Please choose a payment method.'); ?>
                            </div>
                        <?php else: ?>
                            <?php if(isset($this->formErrors['payment_method_error'])): ?>
                                <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                                <?php echo $this->__('Please enter valid details below.'); ?>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                        <div class="cckprd-pay-option-wrapp fl c-pantone">
                            <?php echo $this->getChildHtml('choose-payment-method'); ?>
                        </div>
                    <?php endif; ?>

                    </div>

                    </form> 
		</div>
    </div>
    <!--Shopping bag start-->
    <div class="ckcartright-wrapp fr f-lato">
		<?php echo $this->getChildHtml('summary'); ?>
        <input type="hidden" name="placeorder" value="placeorder" />
        <div class="onestepcheckout-place-order-wrapper place_order" style="display:none;">
            <button type="button" title="<?php echo $this->__('PLACE YOUR ORDER'); ?>" id="onestepcheckout-place-order" class="large orange onestepcheckout-button onestepcheckout-place-order"><?php echo $this->__('Place order now'); ?></button>
        </div>

        <script>
            <?php if($this->hasFormErrors()): ?>
            if($$('div.input-error').length > 0) {
                var input = $$('div.input-error')[0].select('input');
                if(input.length == 1)   {
                    input[0].focus();
                }
            }
            <?php endif; ?>
        </script>

        <?php if(!$this->settings['exclude_region']): ?>
            <script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
            <script type="text/javascript">
            //<![CDATA[
                var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');

                <?php if($this->settings['enable_different_shipping'] && !$this->isVirtual()): ?>
                var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
                <?php endif; ?>
            //]]>
            </script>
        <?php endif; ?>
        
            
<script type="text/javascript">

Event.observe(window, 'load', function() {
    if ($$('div.shopping-cart-totals').length == 1) {
    }
    else    {

        already_placing_order = false;
        review = false;
        reviewmodal = false;

        /* Handle place order click event */
        $$('.onestepcheckout-place-order').each(function(elem){
            elem.observe('click', function(e)   {
                Event.stop(e);
				elem.disabled = true;
               // First validate the form
                var form = new VarienForm('onestepcheckout-form');

                if(!form.validator.validate())  {
                    Event.stop(e);
					elem.disabled = false;
                } else {
                    if(!already_placing_order && $$('.loading-ajax').length <= 0 ) {
                    <?php if(!empty($helper->settings['addressreview']['enable_addressreview'])):?>
                        var addressTemplates = {
                            shipping: '<?php echo str_replace("\r", '', str_replace("\n", '', $helper->settings['addressreview']['shipping_template']));?>',
                            billing: '<?php echo str_replace("\r", '', str_replace("\n", '', $helper->settings['addressreview']['billing_template']));?>'
                        };
                        addressPreview(addressTemplates, 'addressreview');
                        if(!review){
                            review = true;
                            if(!reviewmodal){
                                reviewmodal = new Control.Modal($('addressreview'),{
                                    overlayOpacity: 0.75,
                                    className: 'modal',
                                    fade: true,
                                    closeOnClick: false
                                });
                            }
                            reviewmodal.open();
                            reviewmodal.observe('beforeClose',function(){
                                review = false;
                            });
                            return true;
                            Event.stop(e);
                        } else {
                            reviewmodal.close();
                        }
                    <?php endif;?>
                        already_placing_order = true;

                        var submitelement = $('onestepcheckout-place-order');

                        var loaderelement = new Element('div').
                            addClassName('onestepcheckout-place-order-loading').
                            update('<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif'); ?>" />&nbsp;&nbsp;<?php echo $this->__('Please wait, processing your order...'); ?>');

                        submitelement.parentNode.appendChild(loaderelement);

                        /* Disable button to avoid multiple clicks */
                        submitelement.removeClassName('orange').addClassName('grey');
                        submitelement.disabled = true;

                        /* Submit the form */
                        $('onestepcheckout-form').submit();
                    }
					else{
						elem.disabled = false;
					}
                }
            });
        });


        // This is a separate page
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
        var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

        $$('dl.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
        $$('div.payment-methods input[name="payment\[method\]"]').invoke('observe', 'click', get_separate_save_methods_function(url));

        $$('div.payment-methods input[name="payment\[method\]"]').invoke('observe', 'click', function() {
            $$('div.onestepcheckout-payment-method-error').each(function(item) {
                new Effect.Fade(item);
            });
        });

        $$('dl.shipment-methods input').invoke('observe', 'click', function() {
            $$('div.onestepcheckout-shipment-method-error').each(function(item) {
                new Effect.Fade(item);
            });
        });

        var has_hidden_terms = false;

        if($('id_accept_terms') != null)    {

            $('id_accept_terms').observe('click', function(e)   {
                var element = e.element();

                if(element.checked) {
                    $$('div.onestepcheckout-terms-error').each(function(item) {
                        new Effect.Fade(item);
                        has_hidden_terms = true;
                    });
                }
                else    {
                    if(has_hidden_terms)    {
                        $$('div.onestepcheckout-terms-error').each(function(item) {
                            new Effect.Appear(item);
                            has_hidden_terms = false;
                        });
                    }
                }
            });
        }
    }
	
    var form = $('onestepcheckout-form');

    /* Highlight selected payment method if one set */
    if($RF(form, 'payment[method]') != null)    {
        try {
            var payment_method = $RF(form, 'payment[method]');
            $('container_payment_method_' + payment_method).show();
            $('payment_form_' + payment_method).show();
        } catch(err)    {

        }
    }

    /* Set default shipping method if not set */
    if($RF(form, 'shipping_method') == null)    {
        try {
            var method = '<?php echo $this->_getDefaultShippingMethod(); ?>';
            if(method != '')    {
                $('s_method_' + method).checked = true;
                get_separate_save_methods_function(url);
            }
        } catch(err)    {

        }
    }
   //submit what's available on load
   //get_separate_save_methods_function(url)();
   
    if($('shipping:use_for_billing_yes').checked){
			$('billing_address').hide();
	}


$('shipping:use_for_billing_yes').observe('click', function(e)  {
        var element = e.element();
        if(element.checked){
            $('billing_address').hide();
			
			$('shipping:use_for_billing_yes').value="1";
        } else {
			$('shipping:use_for_billing_yes').value="0";
            if($('billing-address-select') && $('billing-address-select').value == ''){
                $('billing_address_list').show()
            }
            $('billing_address').show();
            <?php if(!$this->isCustomerLoggedIn()):?>
            $('billing_address_list').show()
            <?php endif;?>
            <?php if($this->isCustomerLoggedIn()):?>
            if(!$('billing-address-select') && $('billing_address_list').getStyle('display')=='none'){
                $('billing_address_list').show()
            }
            <?php endif;?>
        }

        <?php if($this->settings['enable_ajax_save_billing']): ?>
        get_save_billing_function('<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>', '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>', <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>, true, this)();
        <?php endif; ?>
    });
    <?php
        $triggers = Mage::getStoreConfig('onestepcheckout/ajax_update/ajax_save_billing_fields');
        if(!empty($triggers)){
            $triggers = str_replace('country', 'country_id', $triggers);
            $triggers = str_replace('state/region', 'region_id', $triggers);
            $triggers = explode(',',$triggers);
            if(in_array('region_id',$triggers)){
                $triggers[] = 'region';
            }
        }
    ?>

    <?php if(Mage::getStoreConfig('onestepcheckout/ajax_update/enable_ajax_save_billing') && !empty($triggers)):?>

        var url_save_billing = '<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>';
        var url_set_methods = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
        var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;
        var update_on_initial = false;

        var euvat = $('euvat_action_validate_taxvat');

        if(euvat !== null){
            euvat.observe('click', get_save_billing_function(url_save_billing, url_set_methods, update_payments, true, this));
        }

        triggers = ['<?php echo implode ('\',\'',$triggers)?>'];
        btriggered = [];
        striggered = [];

        <?php
        foreach($triggers as $value){
            echo (($this->getQuote()->getBillingAddress()->getData($value)) ? 'btriggered.push(\'billing:'.$value.'\');' : '');
            echo (($this->getQuote()->getShippingAddress()->getData($value)) ? 'striggered.push(\'shipping:'.$value.'\');' : '');
        }
        ?>


        bcountry_id = $('billing:country_id');
        if(bcountry_id){
            if(bcountry_id.getValue()){
                if(!btriggered.include('billing:country_id')){
                    btriggered.push('billing:country_id');
                }
            }
        }
        scountry_id = $('shipping:country_id');
        if(scountry_id){
            if(scountry_id.getValue()){
                if(!striggered.include('shipping:country_id')){
                    striggered.push('shipping:country_id');
                }
            }
        }

        batriggered = false;
        satriggered = false;

        triggers.each(function(item){
            var belement = $('billing:'+item);
            if(belement){
                belement.observe('change', function(e){
                    id = e.element().id;
                    if(!btriggered.include(id)){
                        btriggered.push(id);
                    }
                    if(btriggered.length >= triggers.length-1){
                        batriggered = true;
                    }
                    get_save_billing_function(url_save_billing, url_set_methods, update_payments, batriggered, this)();
                });
            }

            var selement = $('shipping:'+item);
            if(selement){
                selement.observe('change', function(e){
                    id = e.element().id;
                    if(!striggered.include(id)){
                        striggered.push(id);
                    }
                    if(striggered.length >= triggers.length-1){
                        satriggered = true;
                    }
                   get_save_billing_function(url_save_billing, url_set_methods, update_payments, satriggered, this)();
                });
            }
        });
        
        // only for opera mini
        $('ship_pincode_search').observe('click', function() {
		  get_save_billing_function(url_save_billing, url_set_methods, update_payments, true, this)();
		});
		
		$('bill_pincode_search').observe('click', function() {
		  get_save_billing_function(url_save_billing, url_set_methods, update_payments, this, this)();
		});
		// only for opera mini
        
        <?php if($this->isCustomerLoggedIn()):?>
            var bselect = $('billing-address-select');
            var sselect = $('shipping-address-select');
            if(bselect){
                bselect.observe('change', get_save_billing_function(url_save_billing, url_set_methods, update_payments, true, this));
            }
            if(sselect){
                sselect.observe('change', get_save_billing_function(url_save_billing, url_set_methods, update_payments, true, this));
            }
        <?php endif;?>

    <?php endif; ?>

});

if($('payment-tool-tip-close')){
    Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
}
jQuery.noConflict();
jQuery(function(){jQuery(".useforbilling").uniform();});
jQuery(function(){jQuery("select").not("#currency_switcher").uniform();});

jQuery(window).bind("load", function(){
	jQuery("#onestepcheckout-form div#uniform-billing-address-select").one("click",function(){
		jQuery(".Chrome .onestepcheckout-index-index #uniform-billing-address-select span").css({position:'relative',top:'3px'});
		jQuery(".Mac .onestepcheckout-index-index #uniform-billing-address-select span").css({position:'relative',top:'3px'});
	});
	jQuery("#onestepcheckout-form div#uniform-shipping-address-select").one("click",function(){
		jQuery(".Chrome .onestepcheckout-index-index #uniform-shipping-address-select span").css({position:'relative',top:'3px'});
		jQuery(".Mac .onestepcheckout-index-index #uniform-shipping-address-select span").css({position:'relative',top:'3px'});
	});
});
</script>

        
    </div>
    
<?php endif; ?>
</div>
 
<div id="onestepcheckout_popup_overlay" style="display: none;">&nbsp;</div>
<div id="loading-process" style="display: none;"></div>
<script type="text/javascript">
	jQuery(document).ready(function() {
		if (navigator.userAgent.indexOf('Opera Mini') > -1){
			jQuery("#bill_pincode_search").show();
			jQuery("#ship_pincode_search").show();
			jQuery('.input-postcode .reg-success').css({
				'float':'left'
				});
			jQuery('.input-postcode .reg-success input').css({
				'margin':'0px'
				});
		}
	});

    jQuery(document).ready(function(){
        jQuery("a.tab").click(function() {
			if(!jQuery(this).hasClass("disabled")){
				// switch all tabs off
				jQuery("#tabs-new .active").removeClass("active");
				// switch this tab on
				jQuery(this).addClass("active");
				// hide all content
				jQuery(".ckcontent-main").hide();
				// show this content
				var content_show = jQuery(this).attr("name");
				
				var reltouse = jQuery(this).attr("rel");
				
				jQuery("a.tab").each(function(){
					if(jQuery(this).attr('rel') > reltouse){
						jQuery(this).addClass("disabled");
					}
				});
				showShippingDetail();
				jQuery("#"+content_show).show();
			}
        });
		if(jQuery(".shipping-tab-passed").val() == '1'){
			jQuery("#tabs-new ul.sidebar li a.tab").each(function(){
				if(!jQuery(this).hasClass("disabled")){
					jQuery(this).removeClass("disabled");
				}
			});
		}
		
		jQuery("#tabs-new ul.sidebar li a.tab").each(function(){
			if(jQuery(this).hasClass("active")){
				var name = jQuery(this).attr("name");
				jQuery("#"+name).show();
			}else{
				var name = jQuery(this).attr("name");
				jQuery("#"+name).hide();
			}
		});
    });
    
	function validateShippingTab(){
		var checkout = new VarienForm('onestepcheckout-form', true);
		
		if(checkout.validator.validate()){
			var login = jQuery.ajax({
				url: "<?php echo $this->getUrl('onestepcheckout/index/validateShippingTab/') ?>",
				beforeSend: function() {
					jQuery('#delivery-loader').show();
				},
				success: function(result){
					get_save_billing_function('<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>', '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>', <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>, true, this)();
					
					jQuery("ul.sidebar a.two").removeClass("active");
					jQuery("#content_2").hide();
					jQuery("ul.sidebar a.three").removeClass("disabled");
										
					jQuery("ul.sidebar a.three").addClass("active");
										
					jQuery("#content_3").show();
					
					jQuery("span.customer-number").text("+91"+result);
					
					jQuery("input[name=shippingtabpassed]").val("1");
					jQuery('#delivery-loader').hide();
					jQuery("#checkout-payment").removeClass('ck-payment').addClass('ck-payment-ac');
				}
			});
		}
	}

	jQuery("#add-new-address").click(function() {
            togalAddNewAddress();
	});
function togalAddNewAddress() {
    jQuery("#list-of-addresses").show();
    jQuery("#add-new-address").hide();
    jQuery("#shipping_address_list").fadeIn();
    jQuery("#list-shipping-address").fadeOut();
    jQuery("[name='shipping_address_id']").val('');
    jQuery("[name='shipping[firstname]']").val('');
    jQuery("[name='shipping[telephone]']").val('');
    jQuery("[name='shipping[street][]']").val('');		
    jQuery("[name='shipping[postcode]']").val('');
    jQuery("[name='shipping[city]']").val('');
    jQuery("div.input-region").find('span').html('');
    jQuery("#add-new-address").hide();
    jQuery("[name='shipping[save_in_address_book]']").val(1);
}
function orderNow() {
	jQuery(".giftCard").show();
	jQuery(".gc-closebtn").click(function(){
		jQuery(".giftCard").fadeOut();
		});
}
</script>

<script type="text/javascript">

//<![CDATA[
function buyEvoucher(buyparams)
{
	new Ajax.Updater(
		'responsefield',
		'<?php echo $this->getUrl('checkout/cart/removeitemfromcart') ?>',
		{
			onCreate: function() { jQuery("#ajax-loader").show(); jQuery(".giftCard").fadeOut(); },
			onComplete: function() {jQuery("#ajax-loader").show(); jQuery(".giftCard").fadeOut(); },
			parameters : {buyparams : buyparams},
			onSuccess: function(response) { 
			location.reload('<?php echo $this->getUrl('checkout/cart/') ?>');
		  }
		}
	);
}

function deleteShippingAddress(addressId) {
	jQuery.ajax({
		url: "<?php echo $this->getUrl('checkout/cart/deleteShippingAddress/') ?>",
		data: {address_id: addressId},
		type:'POST',
		success: function(data){
			jQuery('#cart-loader-'+addressId).show();
			if(data == '1'){
				window.location.reload();
			}
			else{
				alert(data);
			}
		}
	});		
}

function editShippingAddress(addressId) {
	jQuery("ul.sidebar a.one").removeClass("active");
	jQuery("#content_1").hide();
	jQuery("ul.sidebar a.two").removeClass("disabled");						
	jQuery("ul.sidebar a.two").addClass("active");						
	jQuery("#content_2").show();
	jQuery("#content_3").hide();
	jQuery("#paystp3").addClass("ck-pay-tabfw disabled");
	jQuery("#list-shipping-address").hide();
	jQuery("#shipping_address_list").show();
	jQuery( "#add-new-address" ).hide();
	var data = jQuery('#shipping_address_text_'+addressId).text();
	var arr = data.split('~');
	jQuery("[name='shipping[firstname]']").val(arr[0]);
	jQuery("[name='shipping[telephone]']").val(arr[1]);
	
	if(jQuery("div.input-address-short").find("input").hasClass('street1')) {
		jQuery(".street1").val(arr[2]);
	}
	if(jQuery("div.input-address-short").find("input").hasClass('street2')) {
		jQuery(".street2").val(arr[3]);
	}
	jQuery("[name='shipping[postcode]']").val(arr[4]);
	jQuery("[name='shipping[city]']").val(arr[5]);
	jQuery("div.input-region").find('span').html(arr[6]);	
	jQuery("[name='shipping[country_id]']").val(arr[7]);
}

function chooseShipping(val) {
	jQuery("#shipping-address-select").val(val);
}

jQuery( "#list-of-addresses" ).click(function() {
	togalBackToSavedAddress();
});

function togalBackToSavedAddress() {
    jQuery( "#list-shipping-address" ).show();
    jQuery( "#shipping_address_list" ).hide();	
    jQuery("#list-of-addresses").hide();
    jQuery("#add-new-address").show();		
    jQuery( "#add-new-address" ).show();
    jQuery("[name='shipping[save_in_address_book]']").val(0);
    if(jQuery("#shipping-address-select").val() == '') { jQuery("#shipping-address-select").val(jQuery("#tmp_shipping_address_id").val());}
}

<?php if($this->customerHasAddresses() && !$this->getNewAddressSelectValueOnError('shipping')) {
    ?>
        togalBackToSavedAddress();
    <?php
} else {
    ?>
        togalAddNewAddress();
    <?php
} ?>
//]]>
</script>
<div class="giftCard" style="display: none;">
<div class="giftCardconf-Box">
<a class="gc-closebtn crossbtn" href="#"></a>
<p class="giftCard-text"><span style="font:bold 25px Arial, Helvetica, sans-serif; color:#dd3848; padding:0 0 0 10px;">Hey!</span> <span style="font:bold 14px Arial, Helvetica, sans-serif; color:#122957;">You can only purchase</span> <span style="font:14px Arial, Helvetica, sans-serif; color:#dd3848;"> evoucher or product </span> <span style="font:14px Arial, Helvetica, sans-serif; color:#122957;">at a time.</span></p>
<div class="clear"></div>
<a href="javascript:void(0);" onclick="buyEvoucher('giftcard');" class="redbg redbtnlink ">Buy E-voucher</a>
<a href="javascript:void(0);" onclick="buyEvoucher('normalproduct');" class="bluebg bluebtnlink ">Buy Product</a>
</div>
</div>

<!-- Advertiser 'Ignitee Digital Services Pvt Ltd.-THE AMERICAN SWAN LIFESTYLE COMPANY PVT LTD',  Include user in segment '1544425_THE AMERICAN SWAN LIFESTYLE COMPANY_SRT_Pixel_042913' - DO NOT MODIFY THIS PIXEL IN ANY WAY -->
<img src="http://ad.yieldmanager.com/pixel?id=2366136&t=2" width="1" height="1" />
<!-- End of segment tag -->
