<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
$_quote = Mage::getSingleton('checkout/session')->getQuote();
$coupon_code = $_quote->getCouponCode();
$customerLoginStatus = Mage::getSingleton('customer/session')->isLoggedIn();
$itemArr = Mage::helper('common')->getItemByType();
?>
<div class="onestepcheckout-summary">
<div class="checkout-shopping-bag">    
     
<div class="ckorder-txt fl">Order Summary</div>
<div class="clear"></div>   
<div class="cart_item scroll" id="cart_item">
    <?php $i =0; foreach ($this->getItems() as $item): ?>
    <div class="ck-prd-wrapp">
        <div class="ckprd-img-thumb fl">
			<?php $_product = $item->getProduct(); ?>
			<img width="80" height="84" alt="" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(80, 84); ?>" />
		</div>
        <div class="ckperd-disc-wrapp">
		  <p class="ckprd-item-name bold"><?php echo $item->getName(); ?></p>
		  <div class="ckprd-item-wrap">
			<?php 
					/*$_origPrice = Mage::helper('common')->currency($item->getProduct()->getPrice(), false);
					if ($checkoutHelper->settings['display_tax_included']): 
						$_newPrice = $this->helper('checkout')->getSubtotalInclTax($item);
						if (($_origPrice * $item->getQty()) > $_newPrice):
						$_finalPrice = $_origPrice * $item->getQty();
						$_price = $this->helper('checkout')->formatPrice($_newPrice);
			?>
						<div class="ckprd-item-value"><s><?php echo $this->helper('checkout')->formatPrice($_finalPrice); ?></s></div>
						<div class="ckprd-item-value-disc"><?php echo $_price; ?></div>
						<?php $_savePercent = round((($_finalPrice-$_newPrice)*100 ) / $_finalPrice); ?>
						<?php if($_savePercent) { ?>
						<div class="ckprd-item-disc-pect">(<?php echo $_savePercent; ?>% Off)</div>
						<?php } ?>
				<?php else: ?>
						<div class="ckprd-item-value-disc"><?php echo $this->helper('checkout')->formatPrice($_newPrice); ?></div>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
			<?php endif;*/ ?>
			
			<?php
				$_origPrice = Mage::helper('common')->currency($item->getProduct()->getPrice(), false);
				$_finalPrice = Mage::helper('common')->currency($item->getProduct()->getFinalPrice(), false);
				$_savePercent = round((($_origPrice-$_finalPrice)*100 ) / $_origPrice);
			?>
			
			<?php if($_origPrice > $_finalPrice ) { ?>
			<div class="ckprd-item-value"><s><?php echo $this->helper('checkout')->formatPrice($_origPrice); ?></s></div>	
			<div class="ckprd-item-value-disc"><?php echo $this->helper('checkout')->formatPrice($_finalPrice); ?></div>
			<?php }
				else{ 
				$_newPrice = $this->helper('checkout')->getSubtotalInclTax($item);
				if($_origPrice <= 0 ){$_origPrice = $_newPrice; }
			?>
			<div class="ckprd-item-value-disc"><?php echo $this->helper('checkout')->formatPrice($_origPrice); ?></div>
			<?php } ?>
			
			<?php if($_savePercent) { ?>
				<div class="ckprd-item-disc-pect">(<?php echo $_savePercent; ?>% Off)</div>
			<?php } ?>
						
		  </div>
		  <div class="clear"></div>
		  <?php 
				if ($checkoutHelper->settings['show_custom_options']) {
					$options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct());
					if (isset($options['options']) && count($options['options']) > 0) {
						foreach($options['options'] as $option) {
							echo '<p class="prd-sqc-item">'.$option['label'].': '.$option['value'].'</p>';
						} 
					} 
						
					if ($item->getProduct()->isConfigurable()) {
						$configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
						if (is_array($configurable_options) && count($configurable_options) > 0) {
							foreach($configurable_options as $option) { 
								echo '<p class="prd-sqc-item">'.$option['label'].': '.$option['value'].'</p>';
							}
						}
					}
				}
			 ?>
		  <p class="prd-sqc-item"> <span class="fl">Qty :</span> <span class="ckqunt-sel-area"><input class="qty" id="update_qty_<?php echo $item->getId(); ?>" size="1" maxlength="2" type="text" name="cart[<?php echo $item->getId() ?>][qty]" value="<?php echo $item->getQty(); ?>" onblur="updateQty(<?php echo $item->getId() ?>);"></span></p>
		  <p class="prd-sqc-item"> <a href="<?php echo Mage::getBaseUrl().'checkout/cart/configure/id/'.$item->getId().'/' ?>" class="ckshop-bag-text fl">edit</a> <a href="javascript:removeProduct('<?php echo $item->getId(); ?>')" class="ckremove-btn-new fl">Remove</a></p>
		  <div id="cart-loader-<?php echo $item->getId(); ?>" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>"></div>
		</div>
    </div>
    <?php $i++; endforeach; ?>
    
    <div class="clear"></div>
</div>

<div class="ckprd-tprice-wrpp fl" id="grand_total">
<div class="ckprd-tprice-inner">
	<span class="ckprd-tp-subvalue fl">Items</span>
  <div class="ckprd-tamount fr"><?php echo Mage::getSingleton('checkout/cart')->getSummaryQty(); ?></div>
  <div class="clear"></div>
    <?php foreach ($this->getTotals() as $total): ?>
        <?php if (!$total->getTitle() || $total->getCode() == "giftcardaccount") { continue; } ?>
            <?php
                $code = $total->getCode();
                $value = $total->getValue();
                if ($code == 'subtotal') {
                    $total_name = $this->__('<span class="ckprd-tp-subvalue fl">Sub Total ( Incl. of Tax )</span>');
                } elseif ($code == 'shipping') {
                    $total_name = $this->__('<span class="ckprd-shipp-vat-store fl"> Delivery</span>');
                    if ($checkoutHelper->settings['display_tax_included']) {
                        $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
                    }
                } elseif ($code == 'tax') {
                    $taxDiscount = "";
					$total_name = '';
                    $fullInfo = $total->getFullInfo();
                    if (!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']){
                        $total_name .= '';
                        foreach ($fullInfo as $info):
                            $rates = current($info['rates']);
                            $amount = $info['amount'];
                            $taxDiscount .= '<div id="vat-tax-text" style="display:none;"><span class="ckprd-shipp-vat-store fl">' . $rates['title'] . ' (' . $rates['percent'] . '%)</span> <span class="ckprd-shipp-vat-store fr">' . $this->helper('checkout')->formatPrice($amount) . '</span></div>
                                             <div class="clear"></div>';
                        endforeach;
                    }
					$total_name .= '<span class="ckprd-shipp-vat-store fl" id="vat-tax">VAT & Tax</span>';	
                } elseif($code == 'rewardspent') {
                    $total_name = $this->__('<span class="ckprd-shipp-vat-store fl">You Will Spend</span>');
                    $value = Mage::getSingleton('rewards/session')->getTotalPointsSpendingAsStringList();
                } elseif ($code == 'rewardearned') {
                    $total_name = $this->__('<span class="ckprd-shipp-vat-store fl">You Will Earn</span>');
                }else {
                    $total_name = '<span class="ckprd-shipp-vat-store fl">'.$total->getTitle().'</span>';
                }
           ?>

           <?php
				if ($code != 'grand_total'){
					echo $total_name;
					if ($code == 'subtotal') {
						echo '<div class="ckprd-tamount fr">'.$this->helper('checkout')->formatPrice($value).'</div><div class="clear"></div>';
					}
					elseif($code == 'rewardspent') {
					   echo '<span class="ckprd-shipp-vat-store fr">'.Mage::getSingleton('rewards/session')->getTotalPointsSpendingAsStringList().'</span><div class="clear"></div>';
					} elseif ($code == 'rewardearned') {
						 echo '<span class="ckprd-shipp-vat-store fr">'.Mage::getSingleton('rewards/session')->getTotalPointsEarningAsStringList().'</span><div class="clear"></div>';
					} else{
						echo '<span class="ckprd-shipp-vat-store fr">'.$this->helper('checkout')->formatPrice($value).'</span><div class="clear"></div>';
					}
				}
				if ($code == 'tax') {
					echo $taxDiscount;
				}
            ?>
        <?php endforeach; ?>
	</div>
	<div class="clear"></div>
	<div class="cktotal-p-wrapp">
		<?php foreach ($this->getTotals() as $total):?>
        <?php if (!$total->getTitle()) { continue; } ?>
            <?php
                $code = $total->getCode();
                $value = $total->getValue();
				if($code == 'grand_total') {
                    $total_name = $this->__('<div class="tot-txt fs15 f-bold c-pantone ">Grand Total:</div>');
					echo $total_name;
					echo '<div class="tot-price c-032 f-bold fs15 tt-l">'.$this->helper('checkout')->formatPrice($value).'</div> ';
                }
			?>
		<?php endforeach; ?>
		
		<?php if ($this->needDisplayBaseGrandtotal()):?>
			<div class="tot-txt"><?php echo $this->helper('sales')->__('You will be charged for:') ?></div>
			<div class="tot-price"><?php echo $this->displayBaseGrandtotal() ?></div>
			</div>
		<?php endif?>
	</div>
	
</div>
<?php if(!in_array('giftcard', $itemArr) && (in_array('configurable', $itemArr) || in_array('simple', $itemArr) )) { ?>
<div id="promocode-section" class="ckprd-tprice-wrpp fl" style="display:none;">
	<div class="ck-promo-coup-wrap">
        <p class="ck-promo-txt fl mar-b5">Promotional Coupon</p>
        <div class="clear"></div>
          <input class="cklargefield-email validate-email fl promochk" id="coupon_code" name="coupon_code"  value="<?php echo $coupon_code; ?>" type="text">
          <button class="promo-apply-btn mar mar-none fl" type="button" onclick="removeCoupon(0);">Apply</button>
          <?php $hide_show = (isset($coupon_code) && !empty($coupon_code)) ? '' : ' style="display:none;"'; ?> 
          <span id="coupon-response" <?php echo $hide_show; ?> class="c-pantone fs11 mt5 fl">Coupon Successfully Applied</span> 
          <?php if(isset($coupon_code) && !empty($coupon_code)) { ?>
		  <a class="ckremove-btn-new fl ml10" href="javascript:removeCoupon(1);">Remove</a>		   
          <?php } ?>
          <div id="promo-loader" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>"></div>
      </div>
      </div>
</div>
<?php } ?>
<div id="shipping-address" class="shipping-address" style="display:none;">
<?php
	if(is_object($_quote)){
		$shipping_address = $_quote->getShippingAddress();
		if(!empty($shipping_address)){ ?>
			<div class="ckship-ad-head fl"> Shipping Address</div>
			<div class="fr mar-r20"><a class="ckshop-bag-text fl" href="javascript:void(0);" onclick="editShipping();">edit</a></div>		
				<div class="ckprd-tprice-wrpp c-pantone fl">
					<div class="ckship-ad-txt">
						<div class="mb5"><span class="bold pr5">Name :</span><?php echo $shipping_address->getName(); ?></div>
						
						<div><span class="bold pr5">Address :</span><?php if( is_array($shipping_address->getStreet())) { echo implode(',', $shipping_address->getStreet()); } ?>, <?php echo $shipping_address->getCity(); ?>, <?php echo $shipping_address->getRegion(); ?>, 
						<?php echo $shipping_address->getPostcode(); ?>, <?php echo "India"; ?></div>
						
						<div class="mt5"><span class="bold pr5">Mobile :</span> +91 <?php echo $shipping_address->getTelephone(); ?></div>
						
				</div>
			</div>
		</div>	
	<?php					
		}
	}
?>
</div>    

<script type="text/javascript">
//<![CDATA[
    var total = <?php echo $this->getGrandTotal(); ?>;
    if(payment.reloadcallback){
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure' => true)); ?>';
        paymentrefresh(url);
        payment.countreload = 0;
        payment.reloadcallback = false;
    }

	function showShippingDetail(){
		if(jQuery(".shipping-tab-passed").val() == '1'){
			if(jQuery("#paystp3").hasClass("active")){
				jQuery("#shipping-address").show();
				jQuery("#cart_item").hide();
			}else{
				jQuery("#shipping-address").hide();
				jQuery("#cart_item").show();
				jQuery("#promocode-section").show();
			}			
		}
		else{
			jQuery("#promocode-section").show();
		}
	}
	showShippingDetail();
	
	
	function removeProduct(id) {
		jQuery('#cart-loader-'+id).show();
		jQuery.ajax({
			url: "<?php echo $this->getUrl('onestepcheckout/ajax/ajaxremoveitemcheckout/') ?>",
			data: {id:id},
			type:'POST',
			success: function(data){
				jQuery('#cart-loader-'+id).hide();
				if(data == '1'){
					window.location.reload();
				}
				else{
					alert(data);
				}
			}
		});
	}
	
	function editShipping() {
		jQuery("ul.sidebar a.one").removeClass("active");
		jQuery("#content_1").hide();
		jQuery("ul.sidebar a.two").removeClass("disabled");						
		jQuery("ul.sidebar a.two").addClass("active");						
		jQuery("#content_2").show();
		jQuery("#content_3").hide();
		jQuery("#paystp3").addClass("ck-pay-tabfw disabled");
	}
	
	function updateQty(indx) {
		var formData = jQuery("#update_qty_"+indx).serialize();
		jQuery('#cart-loader-'+indx).show();
		jQuery.ajax({
			url: "<?php echo $this->getUrl('checkout/cart/updateQty/') ?>",
			data: formData,
			type:'POST',
			success: function(data){
				jQuery('#cart-loader-'+indx).show();
				if(data == '1'){
					window.location.reload();
				}
				else{
					alert(data);
				}
			}
		});		
	}
	
	function removeCoupon(val) {
		var coupon_code = jQuery("#coupon_code").val();
		if(coupon_code == '') {
			jQuery("#coupon-response").addClass("c-032").html('Please enter coupon code').show();
			return false;
		}
		else {
			jQuery('#promo-loader').show();
			jQuery.ajax({
				url: "<?php echo $this->getUrl('checkout/cart/applycouponpost/') ?>",
				data: {coupon_code:coupon_code, remove:val},
				type:'POST',
				success: function(data){
					jQuery('#promo-loader').hide();
					var resArr = data.split('~');
					if(resArr[1] == '1'){
						jQuery("#coupon-response").removeClass("c-032").html(resArr[0]);
						window.location.reload();
					}
					else{
						jQuery("#coupon-response").addClass("c-032").html(data).show();
					}
				}
			});
		}
	}
	
	jQuery( "#vat-tax" ).click(function() {
		jQuery( "#vat-tax-text" ).toggle();
	});
		
//]]>
</script>
