<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div id="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
        
<header id="header">
        <?php echo $this->getChildHtml('header', false) ?>
   </header> 
       
           <div id="middle">
              <?php echo $this->getChildHtml('global_messages') ?>
              <?php echo $this->getChildHtml('content') ?>
               
            
        </div>
        <footer id="footer">
        <?php echo $this->getChildHtml('footer') ?>
</footer>
        <?php echo $this->getChildHtml('before_body_end') ?>

</div>
<?php //echo Mage::helper('common')->getGTMCode(); ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
