<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body>
	<?php echo $this->getChildHtml('after_body_start') ?>
<div id="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
<header id="header">
	<?php echo $this->getChildHtml('header') ?>
</header> 
<div id="middle">
<div class="page-holder">
	<div class="bredcrum"><?php echo $this->getChildHtml('breadcrumbs') ?></div>
	<?php echo $this->getChildHtml('global_messages') ?>
	
	<div class="cmscontent">
		
		<?php echo $this->getChildHtml('content') ?>
	</div>
	</div>
</div>
<footer id="footer">
	<?php echo $this->getChildHtml('footer') ?>
</footer>
	<?php echo $this->getChildHtml('before_body_end') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
