<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div id="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
        
<header id="header">
        <?php echo $this->getChildHtml('header') ?>
</header>
<div id="middle">
<?php  
	$action = Mage::app()->getFrontController()->getAction()->getFullActionName('_');
	if($action == 'customer_account_index'){
	?>
		<div class="pagename"><h2><?php echo $this->__('My Account') ?></div>
	<?php 
	}
	if($action == 'customer_address_index'){
	?>
		<div class="pagename"><h2><?php echo $this->__('My Address') ?></div>
	<?php 
	}
	if($action == 'enterprise_invitation_index_index'){
	?>
		<div class="pagename"><h2><?php echo $this->__('My Referrals') ?></div>
	<?php 
	}
	if($action == 'sales_order_history'){
	?>
		<div class="pagename"><h2><?php echo $this->__('My Orders') ?></div>
	<?php 
	}
	if($action == 'customer_account_wallet'){
	?>
		<div class="pagename"><h2><?php echo $this->__('My Wallet') ?></div>
	<?php 
	}
	if($action == 'customer_account_coupons'){
	?>
		<div class="pagename"><h2><?php echo $this->__('My Coupons') ?></div>
	<?php 
	}
	if($action == 'enterprise_customerbalance_info_index'){
	?>
		<div class="pagename"><h2><?php echo $this->__('My Store Credit') ?></div>
	<?php 
	}
	if($action == 'enterprise_giftcardaccount_customer_index'){
	?>
		<div class="pagename"><h2><?php echo $this->__('My Evoucher') ?></div>
	<?php 
	}
 ?>   
<div class="page-holder">
<div id="accountsection">
<div id="accountleft">
<?php 
$customerinfo = Mage::getSingleton('customer/session');
if($customerinfo->isLoggedIn()){
	$customer = Mage::getSingleton('customer/session')->getCustomer();
	if($customer->getGender() == '1'){
	?>
	<div class="profilepic"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/enterprise/aswan/images/guy-icon.jpg" /></div>
	<?php
	}
	else{
	?>
	<div class="profilepic"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/enterprise/aswan/images/girl-icon.jpg" /></div>
	<?php 
	}
?>	
<?php 
}
?>
<div class="accountlinks">
<?php echo $this->getChildHtml('left') ?>
</div>
</div>
<div id="commonright">
<?php echo $this->getChildHtml('global_messages') ?>
<?php echo $this->getChildHtml('content') ?>
</div>
</div>
</div>
<footer id="footer">
    <?php echo $this->getChildHtml('footer') ?>
</footer>
    <?php echo $this->getChildHtml('before_body_end') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
