<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head') ?>
<?php echo $this->getChildHtml('after_body_start') ?>
</head>
<body>
	 <div class="top-info-bar"></div>
    <?php echo $this->getChildHtml('global_notices') ?>
    <div id="container">	
        <?php echo $this->getChildHtml('global_messages') ?>
        <div class="mid-content"><?php echo $this->getChildHtml('content') ?></div>
		<div class="footer-container">
			<div class="feature-cont">
			<?php //echo $this->getChildHtml('footer_before') ?>
			<?php echo $this->getChildHtml('before_body_end') ?>	
			</div>
		</div>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('checkout-footer-v3')->toHtml(); ?>
   </div>
	<?php echo Mage::helper('common')->getGTMCode(); ?>
    <?php echo $this->getAbsoluteFooter(); ?>
</body>
</html>
