<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<?php echo $this->getChildHtml('head') ?>
	<?php echo $this->getChildHtml('after_body_start') ?>
</head>
<body <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
	<div id="top-line"></div>
		
    <?php echo $this->getChildHtml('global_notices') ?>
	
	<header>
		<?php echo $this->getChildHtml('header') ?>
	</header>
	<?php echo $this->getChildHtml('global_messages') ?>
	
	<div class="container">
		<?php echo $this->getChildHtml('content') ?>
	</div>
	<div class="clearfloat" />
	<footer>
		<?php echo $this->getChildHtml('footer_before') ?>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('trends-footer')->toHtml(); ?>
		<?php echo $this->getChildHtml('before_body_end') ?>
	</footer>
	
	<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
