<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" xmlns:fb="http://ogp.me/ns/fb#" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" xmlns:fb="http://ogp.me/ns/fb#" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" xmlns:fb="http://ogp.me/ns/fb#" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" xmlns:fb="http://ogp.me/ns/fb#"> <!--<![endif]-->
<head>
<?php 
echo $this->getChildHtml('head');
echo $this->getChildHtml('after_body_start');
?>
</head>
<body <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    <div class="top-info-bar"></div>
      <div class="as-menu-wrap "></div>
      <div class="as-info-cont">
        <header class=" pos-a">
            <?php echo $this->getChildHtml('header') ?>
       </header>
      </div>
    
    <?php echo $this->getChildHtml('global_notices') ?>
    <div id="container">	
        <?php echo $this->getChildHtml('global_messages') ?>        
        <div role="main">
        	<div class="clearfix" id="bodycontainer">
                <div class="mainbody">
                <div id="itemdetails">
					<?php echo $this->getChildHtml('breadcrumbs') ?>
					<?php echo $this->getChildHtml('content') ?>
				</div>
        </div>
        </div>
			</div>
    </div>
	<footer class="mt40">
			<?php echo $this->getChildHtml('footer_before') ?>
			<?php echo $this->getChildHtml('footer') ?>
			<?php echo $this->getChildHtml('before_body_end') ?>
		</footer>

</body>
</html>
