<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head') ?>
<?php echo $this->getChildHtml('after_body_start') ?>
</head>
<body <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
  <div class="top-info-bar"></div>
      <div class="as-menu-wrap "></div>
      <div class="as-info-cont">
        <header class=" pos-a">
            <?php echo $this->getChildHtml('header') ?>
       </header>
      </div>

    <?php echo $this->getChildHtml('global_notices') ?>

    <div id="container">	
        <?php echo $this->getChildHtml('global_messages') ?>        
        <div role="main">
        	<div id="bodycontainer" class="clearfix">
            	<div class="mainTop"></div>
                <div class="mainbody registration">
					
					<!-- <div class="breadcrumb"> -->
						<?php //echo $this->getChildHtml('breadcrumbs') ?>
					<!-- </div> -->
					
                <?php echo $this->getChildHtml('content') ?>
            </div>
           <div class="mainBot"></div>
            </div>
		<?php //echo $this->getLayout()->createBlock('core/template')->setTemplate('newsletter/footer_subscribe.phtml')->toHtml() ?>
        </div>
    </div>
		<footer>
			<?php echo $this->getChildHtml('footer_before') ?>
			<?php echo $this->getChildHtml('footer') ?>
			<?php echo $this->getChildHtml('before_body_end') ?>
		</footer>

</body>
</html>
