<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php  $_orders = $this->getOrders(); ?>
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>

<div id="orderlist">
<ul>
<?php
$orderStatusArr = array('COD_Verification_Pending'=>'Pending', 'pending'=>'Pending', 'created'=>'In Processing', 'processing'=>'In Processing', 
						'COD_Verification_Successful'=>'COD Verified');
 
foreach ($_orders as $_order): 
	//$status = $_order->getStatusLabel();
	$order_id = $_order->getIncrementId();
	$order = Mage::getModel('sales/order')->loadByIncrementId($order_id); 
	$shipmentCollection = $order->getShipmentsCollection();
	$track_number = '';
	$shipping_url = '';
	foreach($shipmentCollection as $shipment)
	{
		$shipmentIncrementId = $shipment->getIncrementId();
		$shipment=Mage::getModel('sales/order_shipment')->loadByIncrementId($shipmentIncrementId);
		foreach ($shipment->getAllTracks() as $track)
		{
			$track_number=$track->getnumber();
			$track_title=$track->gettitle();
		}
	}
	
	if($track_title != '') {
		$provider = Mage::getModel("provider/provider")->getCollection()->addFilter('shippingprovider_name',$track_title);
		foreach ($provider as $track_provider)
		{
			$shipping_url = $track_provider->getshippingprovider_action();
		}
	}
					 
	$items = $order->getAllVisibleItems();
	$shipping_address = $order->getShippingAddress(); 
	$countryCode = $shipping_address->getData('country_id');
	$country = Mage::getModel('directory/country')->loadByCode($countryCode);
	
	$orderStatus = "Status: ".(isset($orderStatusArr[$_order->getStatus()]) ? $orderStatusArr[$_order->getStatus()] : ucfirst($_order->getStatus()));
	
	if($track_number != '') {
		$orderStatus = $track_title.' ('.$track_number.')';
	}	
?>
 <li>
	<div class="orderhead">
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td><?php echo $_order->getRealOrderId() ?></td>
			<td>Items: <?php echo round($_order->getTotalQtyOrdered()) ?> Qty</td>
			<td><?php echo date("jS M, y", strtotime($_order->getCreatedAtStoreDate())); ?></td>
			<td>Order Value: <?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
			<td><?php echo $orderStatus ?></td>
			<td><a href="#tab_<?php echo $_order->getId();?>" class="details">Track details</a>
		</tr>
	  </table>
	</div>
	 <div class="orderdetail" id="tab_<?php echo $_order->getId();?>">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<?php 
	foreach ($items as $item){
		$product = Mage::getModel('catalog/product')->load($item->getProductId());
		$orderItemOptions = $item->getProductOptions();
		$imageUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product' . $product->getImageUrl();
		$imageCacheUrl = Mage::helper('catalog/image')->init($product, 'image')->resize(320,334);
	?>	
	<tr>
		<td width="50%"><img src="<?php echo $imageCacheUrl;?>" />
		<h3><a href="#"><?php echo $product->getName();?></a></h3>
		<p><?php echo $orderItemOptions['attributes_info'][1]['value'];?>/ <?php echo $orderItemOptions['attributes_info'][0]['value'];?><br />
		Qty : <?php echo (int)$item->getData('qty_ordered');?></p>
		<p><span class="price">Rs<?php echo round($item->getPrice());?></span></p>
      </td>
    <td>
    <h4><?php if($track_number != ''){ echo 'AWB No. : '.$track_number; } ?>
    <br/>
    <?php if(!empty($track_number)) { ?>
    <a href="javascript:void(0);" onclick="track('<?php echo $shipping_url ?>')" target="_blank" class="trackdata" title="Copy AWB No.">Track</a>
    <?php } ?>
		<?php /*<a href="#" class="trackdata" data-row="trackrow_<?php echo $item->getProductId();?>_<?php echo $order_id;?>" title="Copy AWB No.">Track</a> 
		<a class="fancybox" href="#reportissue">Report an issue / Return</a>*/?></h4>
    </td>
  </tr>
   <?php /* <tr class="trackrow" id="trackrow_<?php echo $item->getProductId();?>_<?php echo $order_id;?>">
	<td colspan="2">
		  <ol>
			  <li>Status 1</li>
			  <li>Status 2</li>
			  <li class="current">Status 3</li>
			  <li>Status 4</li>
			  <li>Status 5</li>
			  <li>Status 6</li>
		  </ol>
	</td>
  </tr>*/?>
	 <?php 	 
	}
	?>
	 <tr>
    <td colspan="2">
	<address><strong>Delivery Details:</strong> 
		<?php echo $shipping_address->getData('street');?>,
		<?php echo $shipping_address->getData('city');?>, <?php echo $shipping_address->getData('region');?>, <?php echo $country->getName();?>,<?php echo $shipping_address->getPostcode();?>, T: <?php echo $shipping_address->getTelephone(); ?>
	</address>
	</td>
	</tr> 
</table>
  <?php
  endforeach; 
  ?>
</li>
</ul>
</div>
<?php /*<div class="globlepopup" id="reportissue">
	<input type="radio" name="reportreturn" id="report" data-toggle="tab1" checked="checked"/><label for="report">Report an issue</label>
	<input type="radio" name="reportreturn" id="return" data-toggle="tab2" /> <label for="return">Return</label>
	<input type="radio" name="reportreturn" id="exchange" data-toggle="tab3" /> <label for="exchange">Exchange</label>
	<br />
<div class="rowhold" id="tab1" style="display:block;">
	<select>
		<option selected="selected">Reason ?</option>
		<option>Qty</option>
		<option>Quality</option>
		<option>Size</option>
		<option>Color</option>
		<option>Delivery</option>
		<option>Other</option>
	</select>
</div>
<div class="rowhold" id="tab2">
<select>
	<option selected="selected">Reason ?</option>
	<option>Quality</option>
	<option>Fit</option>
	<option>Size</option>
	<option>Color</option>
	<option>Other</option>
</select>
<select>
	<option selected="selected">Resolution</option>
	<option>Exchange</option>
	<option>Refund</option>
</select>
</div>
<div class="rowhold" id="tab3">
<select>
	<option selected="selected">Reason ?</option>
	<option>Color</option>
	<option>Size</option>
	<option>Other</option>
</select>
<select>
	<option selected="selected">Resolution</option>
	<option>Exchange with other color</option>
	<option>Exchange with white color</option>
	<option>Size L</option>
	<option>Size M</option>
</select>
</div>
<textarea placeholder="Comment"></textarea>
	<a href="#" class="go">Submit</a>
</div>*/?>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
<script>
function track(url) {
	window.open(url,'_blank');
}
</script>

