<ul>
	<?php $_links = $this->getLinks(); ?>
	<?php $_index = 1; ?>
	<?php $_count = count($_links); ?>
	<?php foreach ($_links as $_link): ?>
		<?php $_last = ($_index++ >= $_count); ?>
		<?php if ($this->isActive($_link)): ?>
			<li><a class="active<?php echo ($_last ? ' last' : '') ?>" href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
		<?php else: ?>
			<li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
		<?php endif; ?>
	<?php endforeach; ?>
	<li><a href="<?php echo $this->getUrl('customer/account/wallet');?>">My wallet</a></li>
</ul>

