<?php
/**
 * Product:     Layered Navigation Pro for Enterprise Edition - 16/08/12
 * Package:     AdjustWare_Nav_10.4.9_10.0.0_557110
 * Purchase ID: hXgQU3oI8FOfJ8PDCk5s6h6XPM5oH2Kx0N6TCAPkqN
 * Generated:   2013-04-22 06:59:44
 * File path:   app/design/frontend/enterprise/default/template/adjnav/shopbyjs.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<?php if(Mage::helper('adjnav')->isModuleEnabled('Aitoc_Aitmanufacturers')):?>
<script type="text/javascript">
var currentShopByAttribute = "<?php echo Mage::registry('shopby_attribute');?>";
var currentShopByAttributeValue = "<?php echo Mage::getSingleton('core/session')->getAitocManufacturersCurrentManufacturerId();?>";
</script>
<?php endif;?>