 <table class="listOrders f-lato fs14" width="100%" cellspacing="0" cellpadding="5" border="0">
     <tr><td><?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('customer/account/navigation.phtml')->toHtml(); ?>
 <div class="default_address acc-perdetail fs14 f-lato" style="float: left; width: 700px;">
 <h2 class="title  tt-u mt20 mb10 ml45"><?php echo Mage::helper('enterprise_invitation')->__('Send An Invitation') ?></h2>
<p class="text myrefral-top-txt ml45"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?><?php echo Mage::helper('enterprise_invitation')->__('Invite your friends by entering their email addresses below'); ?></p>
<?php echo $this->getChildHtml('form_before') ?>

<?php if ($maxPerSend = (int) Mage::helper('enterprise_invitation')->getMaxInvitationsPerSend()): ?>

    <table width="100%" cellpadding="5" cellspacing="0" border="0" class="listOrders myrefl-list">
        <tr>
            <td class="emailSrch">
                <form id="form-validate" action="<?php echo $this->getUrl('invitation/index/send/'); ?>" method="post">
                    <label for="email_address" class="required pt5 pb5"><?php echo $this->__('To') ?><span class="mandatoryField">*</span></label>
                    <textarea name="email" cols="60" rows="5" id="email_address" class="validate-emails required-entry"><?php echo $this->getEnteredData('emails') ?></textarea>
                    <div class="pageInfo">Use Commas(,) to separate e-mail addresses.</div>

                <?php if (Mage::helper('enterprise_invitation')->isInvitationMessageAllowed()): ?>
                    <label for="message" class="pt5 pb5"><?php echo Mage::helper('enterprise_invitation')->__('Message'); ?></label>
                    <textarea name="message" id="message" title="<?php echo Mage::helper('enterprise_invitation')->__('Message') ?>"  class="vaildate-message" rows="5" cols="5"></textarea>
                    <div class="pageInfo">Max 500 characters.</div>
                <?php endif; ?>

                    <button type="submit" name="" class="btnsubmit">Send Invitation</button>                   
                    
                </form>
            </td>
        </tr>
        <tr>
            <td class="nopad"><button name="" type="button" class="btnsubmit backlist" onclick="window.location = '<?php echo Mage::helper('enterprise_invitation')->getCustomerInvitationUrl() ?>'"><?php echo Mage::helper('enterprise_invitation')->__('Back To Invitations List') ?></button></td>
        </tr>
    </table>


    <script type="text/javascript">
        //<![CDATA[
        Validation.addAllThese([
            ['validate-emails', '<?php echo $this->__('Please enter a valid email addresses, separated by commas. For example johndoe@domain.com, johnsmith@domain.com.') ?>', function (v) {
                    if(Validation.get('IsEmpty').test(v)) {
                        return true;
                    }

                    var valid_regexp = /^[a-z0-9\._-]{1,30}@([a-z0-9_-]{1,30}\.){1,5}[a-z]{2,4}$/i;
                    var emails = v.split(',');

                    for (var i=0; i<emails.length; i++) {
                        if(!valid_regexp.test(emails[i].strip())) {
                            return false;
                        }
                    }

                    return true;
                }],
            ['vaildate-message', '<?php echo $this->__('Message length should be upto 500 chars.') ?>', function (v) {

                    var len = v.length;
                    if(len > 500) {
                        return false;
                    }else{
                        return true;
                    }
                }]
        ]);
        var dataForm = new VarienForm('form-validate', true);
        //]]>
    </script>
<?php else: ?><p><?php echo Mage::helper('enterprise_invitation')->__('You cannot send more invitations'); ?></p><?php endif; ?>

<script type="text/javascript">
    function popup(url) {

        var newwin;

	var width  = 1000;
	var height = 500;
	var left   = (screen.width  - width)/2;
	var top    = (screen.height - height)/2;
	var params = 'width='+width+', height='+height;
	params += ', top='+top+', left='+left;
	params += ', directories=no';
	params += ', location=no';
	params += ', menubar=no';
	params += ', resizable=no';
	params += ', scrollbars=no';
	params += ', status=no';
	params += ', toolbar=no';
        params += ', modal=yes';

        if (window.showModalDialog) {
            newwin = window.showModalDialog(url,"socialinvite", "resizable:0;dialogWidth:"+width+"px;dialogHeight:"+height+"px;dialogLeft:"+left+";dialogTop:"+top+";center:1;");
        } else {
            newwin = window.open('url','socialinvite',params);
        }
	if (window.focus) {newwin.focus()}
    }
</script>

<h2 class="title myrefral-top-txt fr"><?php echo Mage::helper('enterprise_invitation')->__('INVITATIONS SENT'); ?></h2>
<?php if (count($this->getInvitationCollection())): ?>
	<!--<p class="underline"></p>-->
<?php endif; ?>

<?php echo $this->getChildHtml('list_before') ?>
<?php if (count($this->getInvitationCollection())): ?>
<table width="100%" cellpadding="5" cellspacing="0" border="0" class="listOrders myrefl-list">
<!--    <tr>
        <td colspan="2" class="pagerNav">
            <div class="clearfix pagelist">
                <div class="lftArw"><a href="javascript:void(0);"><img src="{{skin url="images/lftArw.gif"}}" alt="" /></a></div>
                <ul class="num">
                    <li><a href="javascript:void(0);" class="active">1</a></li>
                    <li><a href="javascript:void(0);">2</a></li>
                    <li><a href="javascript:void(0);">3</a></li>
                </ul>
                <div class="rgtArw"><a href="javascript:void(0);"><img src="{{skin url="images/lftArw.gif"}}" alt="" /></a></div>
            </div>
        </td>
    </tr>-->

    

    <?php $i = 0; foreach ($this->getInvitationCollection() as $invitation): ?>
    <tr class="<?php echo ($i % 2) == 0 ? 'oddRow' : 'evenRow'; ?>">
        <td width="30%"><span class="fl invttxt-field"><?php echo $this->htmlEscape($invitation->getEmail()); ?></span></td>
        <td><span class="fl invt-status"><?php echo $this->helper('enterprise_invitation')->getInvitationStatusText($invitation); ?></span></td>
    </tr>
    
    <?php $i++; endforeach; ?>
    
    <tr><td colspan="6" class="heightmgr"></td></tr>

<!--            <tr>
                <td colspan="2" class="pagerNav">
                    <div class="clearfix pagelist">
                        <div class="lftArw"><a href="javascript:void(0);"><img src="{{skin url="images/lftArw.gif"}}" alt="" /></a></div>
                        <ul class="num">
                            <li><a href="javascript:void(0);" class="active">1</a></li>
                            <li><a href="javascript:void(0);">2</a></li>
                            <li><a href="javascript:void(0);">3</a></li>
                        </ul>
                        <div class="rgtArw"><a href="javascript:void(0);"><img src="{{skin url="images/lftArw.gif"}}" alt="" /></a></div>
                    </div>
                </td>
            </tr>-->

</table>
<script type="text/javascript">decorateTable('invitations-list-table')</script>
<?php /* else: ?>

<div id="cookie-notice">
    <ul class="messages">
        <li class="notice-msg">
            <ul><li><?php echo Mage::helper('enterprise_invitation')->__('There are no sent invitations yet'); ?></li></ul>
        </li>
    </ul>
</div>

<?php */
	endif; 
?>
 </div>
         </td>
     </tr>
 </table>