<?php if($this->getCollection()->getSize()): ?>
<div class="">
    <?php if( $this->isExpanded() ): ?>
        <?php if( $this->isEnabledViewSwitcher() ): ?>
        <p class="view-mode">
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>
            <label><?php echo $this->__('View as') ?>:</label>
            <?php $_i=1; $_fix=''; foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if ($_i==1 && strtolower($_code)=='list') $_fix='-fix'; ?>
                <?php if($this->isModeActive($_code)): ?>
                    <strong class="<?php echo strtolower($_code); echo $_fix; ?>" title="<?php echo $_label ?>"><?php echo $_label ?></strong>
                <?php else: ?>
                    <a class="<?php echo strtolower($_code); echo $_fix; ?>" title="<?php echo $_label ?>" href="<?php echo $this->getModeUrl($_code) ?>"><?php echo $_label ?></a>
                <?php endif; ?>
            <?php $_i++; endforeach; ?>
            <?php endif; ?>
        </p>
        <?php endif; ?>
        <?php if(Mage::registry('current_category')) {
            $catImgUrl = '';
            $catImgUrl = Mage::registry('current_category')->getImageUrl();
            if($catImgUrl != '')
                $style = "style='margin-top: -30px;width: 150px;padding:2px 4px;'";
            else
                $style = "style='margin-top:-60px;width: 150px;padding:2px 4px;'";
        }else {
            $style = '';
        }
        ?>
         <div class="Sort" <?php echo $style;  ?> >
            <select onchange="setLocation(this.value)" id="sortby">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): 
                if( $_key != 'price') :
            ?>
                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo $this->__($_order) ?>
                </option>
            <?php endif; endforeach; ?>
                <option value="<?php echo $this->getOrderUrl('price', 'asc') ?>"<?php if($this->isOrderCurrent('price') && $this->getCurrentDirection() == 'asc'): ?> selected="selected"<?php endif; ?>>Price: Low to High</option>
                <option value="<?php echo $this->getOrderUrl('price', 'desc') ?>"<?php if($this->isOrderCurrent('price') && $this->getCurrentDirection() == 'desc'): ?> selected="selected"<?php endif; ?>>Price: High to Low</option>
            </select>           
        </div>
        
    <?php endif; ?>
        <div class="CatTitleLeft">
         <p><?php echo $this->__($this->getTotalNum()) ?> Products Found</p>
         <div class="toolbar" style="display:none;"><?php echo $this->getPagerHtml() ?></div>
        </div>
</div>
<?php endif ?>
