<div class="col-main">
    <div class="page-title">
        <h1>Hey!</h1>
        <div id="l2">Something seems to be wrong..</div>
        <div id="l3">Till then ADD other things to your BASKET.</div>
        <div id="l4">Please clear your cookies and browser cache<br/>by CTRL + Shift + Delete</div>
    </div>
    <div id="img_shop_more"><a href="<?php echo $this->getBaseUrl() ?>"><img src="<?php echo $this->getSkinUrl()?>images/shop_more.png" ></a></div>
    <div id="sep"></div>
    <?php if ($this->reportId && $this->reportUrl): ?>
        <p>Exception log record number: <a href="<?php echo htmlspecialchars($this->reportUrl) ?>"><?php echo $this->reportId ?></a></p>
    <?php endif; ?>
</div>
