<?php
/**
 *
 * @category    design
 * @package     default_default
 * @author     Fsite
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Newsletter Subscription') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Newsletter Subscription') ?></h2>

        <?php $_newslettergroup = $this->getLayout()->createBlock('newslettergroup/widget_group') ?>
        <?php $_newslettergroup->setIsSubscribed($this->getIsSubscribed()) ?>
        <?php $_newslettergroup->setNewsletterGroupId($this->getSubscriptionObject()->getNewsletterGroupId()) ?>
        <?php echo $_newslettergroup->toHtml() ?>

    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
