<?php $aLoyaltyRules = $this->getLoyaltyRulesCustom(); ?>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('customer/account/navigation2.phtml')->toHtml(); ?>
<?php
        //print count($aLoyaltyRules);
        foreach ($aLoyaltyRules as $_rule):
                $actUsed = 0;
                if(!is_null($_rule->getActUsed())){
                        $actUsed = $_rule->getActUsed();
                }
                if(!is_null($_rule->getExpirationDate()) && strtotime($_rule->getExpirationDate()) <= time()) {
                    continue;
                }
                $iCount++;
        endforeach; 
?>
<div class="bgc-fcfc">
    Total coupons in my wallet
    <div style="height: 166px; text-align: center; padding: 5px; background-color: rgb(170, 170, 170); margin-top: 10px;">
        <p style='font-size: 50px; margin-bottom: 15px;'><?php echo (int) $iCount ?> Coupon</p>
        are available to shop
    </div>
</div>
<div style='clear: both;'></div>
<div style="width: 990px;">
<?php $iCount = 0;?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('info');?>

<?php //if($aLoyaltyRules->getSize()): ?>
	<!--<p class="text">You have <strong><?php //echo $aLoyaltyRules->getSize(); ?></strong> coupons</p>-->

<?php if(count($aLoyaltyRules)): ?>
	<p class="underline"></p>

	<table width="100%" cellpadding="5" cellspacing="0" border="0" class="listCoupons">
            <?php if ($this->getPagerHtml() != '') { ?>
		<tr>
			<td colspan="6" class="pagerNav">
				<?php echo $this->getPagerHtml(); ?>
			</td>
		</tr>
            <?php  } ?>
		<tr>
			<th class="couponNo"><?php echo $this->__('Coupon Code') ?></th>
			<th class="couponDesc"><?php echo $this->__('Description') ?></th>
			<th class="couponDt"><?php echo $this->__('Expiry Date') ?></th>
			<th class="couponStatus"><?php echo $this->__('Can Be Used') ?></th>
			<th class="timesused"><?php echo $this->__('Times Used') ?></th>
		</tr>

		<?php $_odd = 1; ?>
		
		<?php
			//print count($aLoyaltyRules);
			foreach ($aLoyaltyRules as $_rule):
				$actUsed = 0;
				if(!is_null($_rule->getActUsed())){
					$actUsed = $_rule->getActUsed();
				}
		?>
		<?php 	$iCount++;	?>
				<tr class="<?php if ($_odd %2 == 0) { echo 'evenRow'; } else { echo 'oddRow';} ?>">
					<td><?php echo wordwrap($_rule->getCode(), 25, "<br>", true); ?></td>
					<td>
						<?php
							if($_rule->getValue()!=''){
								$content = trim($_rule->getValue());
							}else{
								$content = trim($_rule->getName());
							}
							
							print $content;
						?>
					</td>
					<td>
						<?php
							if(is_null($_rule->getExpirationDate())){
								echo 'N/A';
							}else{
								echo $this->formatDate($_rule->getExpirationDate(), 'medium');
							}
						?>
					</td>
					<td>
						<?php
						
							print $_rule->getUsesPerCustomer();
							
						?>
					</td>
					<td><?php echo $actUsed;?></td>
				</tr>
		<?php
			$_odd++;
			endforeach; 
		?>
	
		<!-- <tr>
			<td colspan="6" class="heightmgr">
			</td>
		</tr>-->
                                <?php if ($this->getPagerHtml() != '') { ?>
		<tr>
			<td colspan="6" class="pagerNav">
				<?php echo $this->getPagerHtml(); ?>
			</td>
		</tr>
                                <?php } ?>
	</table>
<?php endif; ?>

<?php if (!$iCount): ?>
    <?php echo $this->helper('sales')->__('No specials currently available') ?>
<?php endif; ?>
                </div>