<div id="myrefrals">
<div class="inviteform">
	<h3>Send An Invitation</h3>
	<div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
	<?php echo $this->getChildHtml('form_before')?>
	<?php if ($maxPerSend = (int)Mage::helper('enterprise_invitation')->getMaxInvitationsPerSend()): ?>
	<form id="invitationForm" action="<?php echo $this->getUrl('invitation/index/send/'); ?>" method="post">
    <p><?php echo Mage::helper('enterprise_invitation')->__('Invite your friends by entering their email addresses below'); ?></p>

            <?php $_perRow = ceil($maxPerSend/3); 
            for($_index = 1; $_index <= $maxPerSend; $_index ++): ?>
            <?php 
				if($_index == 1) :
            ?>
                <label for="email_<?php echo $_index ?>"<?php if ($_index == 1) echo 'class="required"' ?>>
                <?php if ($_index == 1)?></label>
                <div class="input-box">
                    <textarea tabindex="<?php echo $_index ?>" name="email[]" id="email_<?php echo $_index ?>" title="<?php echo Mage::helper('enterprise_invitation')->__('Email') ?>" value="" class="<?php if ($_index == 1): ?>required-entry <?php endif;?>input-text validate-email" /></textarea>
                </div>
				<div class="inputnote">Use Commas(,) to separate e-mail addresses.</div>
            <?php endif; ?>
            <?php endfor; ?>
            
        <?php if (Mage::helper('enterprise_invitation')->isInvitationMessageAllowed()): ?>

                <label for="message"><?php echo Mage::helper('enterprise_invitation')->__('Message');?>: </label>
                <div class="input-box">
                    <textarea onkeyup="countChar(this)" tabindex="<?php echo $_index+1 ?>" name="message" id="message" title="<?php echo Mage::helper('enterprise_invitation')->__('Message') ?>"  class="required-entry input-text"  rows="5" cols="5"></textarea>
                </div>
                <div class="inputnote">Max <span id="charNum">500</span> characters.</div>
                
        <?php endif;?>
<p class="required"><?php echo Mage::helper('enterprise_invitation')->__('') ?></p>
<button class="go" onclick="sendInvitation();"><?php echo Mage::helper('enterprise_invitation')->__('Send Invitations') ?></button>
</div>
</form>
<script type="text/javascript">
	function sendInvitation() {
		var contactForm = new VarienForm('invitationForm', true);
	}
</script>
<?php else:?>
<p><?php echo Mage::helper('enterprise_invitation')->__('You cannot send more invitations'); ?></p>
<?php endif; ?>

<div class="invitesend">
<h3>Invitations Send</h3>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<?php if (count($this->getInvitationCollection())): ?>
	<tr>
		<th><?php echo Mage::helper('enterprise_invitation')->__('Email'); ?></th>
		<th><?php echo Mage::helper('enterprise_invitation')->__('Date'); ?></th>
		<th><?php echo Mage::helper('enterprise_invitation')->__('Status'); ?></th>
	</tr>
    <?php foreach ($this->getInvitationCollection() as $invitation): ?>
        <tr>
            <td><?php echo $this->htmlEscape($invitation->getEmail()); ?></td>
            <td><?php echo date("d M, y", strtotime($invitation->getData('invitation_date'))); ?></td>
            <td><?php echo $this->helper('enterprise_invitation')->getInvitationStatusText($invitation);?></td>
        </tr>
    <?php endforeach; ?>
<script type="text/javascript">decorateTable('invitations-list-table')</script>
<?php else: ?>
<div id="cookie-notice">
    <ul class="messages"><li class="notice-msg">
        <ul><li><?php echo Mage::helper('enterprise_invitation')->__('There are no sent invitations yet'); ?></li></ul>
    </li></ul>
</div>
<?php endif; ?>
</table>
</div>
</div>
<script>
function countChar(val) {
        var len = val.value.length;
        if (len >= 500) {
          val.value = val.value.substring(0, 500);
        } else {
          jQuery('#charNum').text(500 - len);
        }
      };
</script>
