<div id="testimonial_all" class="clearfix itemMain">
    <div class="page_title cartHead"><?php echo Mage::helper('testimonials')->__('Testimonials') ?></div>

	<div class="submit_testimonial">
		<button type="button" onClick="location.href='<?php echo $this->getUrl('testimonials/submit'); ?>'" >
			<?php echo $this->__('Submit Your Testimonial') ?>		   
		</button>
	</div>

	<br class="clear"/>
	<?php $cnt = count($this->getTestimonials()); ?>
	<?php if($cnt > 0 ): ?>
		<?php 
			$c = ceil($cnt/2); 
		
			$i = 0;
		?>
		<?php foreach ($this->getTestimonials() as $item): ?>                  
			<?php
				if ($i == 0) {
			?>
					<div class="left testigroup">
			<?php
				} else if ($i == $c) {
			?>
					<div class="right testigrouprt">
			<?php
				}
			?>	
			<div class="testimonial_body block_t">
				<p><?php echo nl2br(trim($item->getContent())); ?></p>
				<br>
				<span class="tname"><?php   echo trim($item->getName()); ?>, </span><span class="tplace"><?php   echo trim($item->getPlace()); ?></span>
				<div class="bottom_quote"></div>
			 </div>
			 
			 <?php
				$i++;
				if ($i == $c OR $i == $cnt) {
			?>
					</div>
			<?php
				}
			?>
			
		<?php endforeach;  ?> 
		<br class="clear">
		
		<?php echo $this->getPagerHtml(); ?>
		
	<?php else: ?>
		<div class="std">There is no testimonials here</div>
	<?php endif; ?>
	
</div>