<!-- Popup Overlay -->
<div class="sizepopup">
<div class="quickclose"></div>

		

			
			<?php
				$_product = $this->getProduct();
				$sizechart = $_product->getAttributeText('sizechart');
				$counter = 0;
				$collection = Mage::getModel('sizeguide/sizeguide')->getCollection();
				if(isset($sizechart) && $sizechart != '') {	
					$collection->getSelect()->where("sizeguide_id = ? ", (string) $sizechart);
				}
				else {
					$collection->getSelect()->where("sizeguide_id IN (1,2) ");
				}
				//echo $collection->getSelect()->__toString();
				$collection->getSelect()->where('status = 1')->order('order_id ASC');
				$size_popup = sizeof($collection);
				
				if($size_popup <=0 ) {
					$collection->getSelect()->where("sizeguide_id IN (1,2) ");
					$collection->getSelect()->where('status = 1')->order('order_id ASC');
					$size_popup = sizeof($collection);
				}
					
				if($size_popup > 0)	{
			?>
				
					
						
							
       <div class="sizetabs"> 
		<ul>
		<?php
		$imgUrl =  $this->getSkinUrl()."images/sizechart/";
		foreach ($collection as $sizedata):
			$SizeData = $sizedata->getData();
			$content[] = str_replace("##IMG_URL##",$imgUrl,$SizeData['content_size']);
			if(empty($sizechart)) {
        ?>
       
		   <li class="size-tab"><a toggle-tab="tab<?php echo $counter;?>" href="javascript:void(0)"><span><b> 
		   <?php echo $SizeData['title'];?> </b></span></a></li>
		   <?php } ?>
		   <?php $counter++; endforeach; ?>
	</ul>
		</div>					
						
<div>
<?php for($i=0; $i<$size_popup; $i++) { ?>
	<div id="tab<?php echo $i; ?>" style="display:none;">
		<?php echo $content[$i]; ?> 
	</div>
<?php } ?>

					
				
				<?php 
				} else {				
					echo '<h2>No Size Guide Available !</h2>';				
				}
				?>
				
	</div>		

    <script language="javascript">
	
	<?php if($size_popup > 0) { ?>
		jQuery('.sizetabs li:first-child a').addClass('active');
		jQuery('#tab0').show();	
	<?php } ?>
	
	<?php if(empty($sizechart)) { ?>		
		jQuery('#tab0').addClass('active');
	<?php } ?>
	
   jQuery('.sizetabs li a').click(function(){
   	var tabShow = jQuery(this).attr('toggle-tab');
   	jQuery(this).addClass('active');
   	jQuery(this).parent().siblings().find('.active').removeClass('active');

   	jQuery('#'+tabShow).siblings().hide();
   	jQuery('#'+tabShow).siblings().removeClass('active');

   	jQuery('#'+tabShow).show();
   	jQuery('#'+tabShow).addClass('active');

   });

	
</script>
</div>