<div class="cod-avil-section">
    <div class="cod-txt-wrp"><span></span>COD AVAILABLE</div>
    <div class="cod-in-field-sec ">
    	<input type="text" class="cod-input-sec" value="Enter Your Pin" name="zip_code" id="zip_code" onblur="javascript:onBlurText(this,'Enter Your Pin');" onclick="javascript:onClickText(this,'Enter Your Pin');" maxlength="<?php echo Mage::getStoreConfig('zipcodeimport/cod/zipcodelength'); ?>" />
    </div>
    <a href="javascript:void(0);" onclick="javascript:submitCodForm();" id="gtm-pincode-check" class="cod-check-btn gtm-track">Check</a>
    <div class="clear"></div>
	<span id="response" style="display:none;" class="cod-msg-txt"><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> </span>
</div>
<script type="text/javascript">
    function submitCodForm(){
        var data = "zip_code="+jQuery("#zip_code").val();
        var url = '<?php echo $this->getUrl('zipcodeimport/index/getCodAvailability') ?>';
        jQuery("#response").html('<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" />');
        jQuery("#response").css('display', 'inline');
        jQuery.post(url, data, function(response){            
            jQuery("#response").html(response);
        });
    }
    function onClickText(object,value){
        if(object.value == value){
            object.value = '';
        }
    }
    function onBlurText(object,value){
        if(object.value == ''){
            object.value = value;
        }
    }
	jQuery("#zip_code").keypress(function(event){
		if(event.keyCode == 13){
			event.preventDefault();
			submitCodForm();
		}
	});
</script>
