<?php
/**
 *
 * @category    design
 * @package     default_default
 * @author     Fsite
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-newsletter-list"><?php echo $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
<!--                <button class="scalable add" onclick="window.location='<?php //echo $this->getCreateUrl() ?>'"><span><?php //echo Mage::helper('newsletter')->__('Add New Group'); ?></span></button>-->
            </td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getChildHtml('grid') ?>
</div>
