<!-- [start] center -->
    <div id="main" class="col-main">
    <!-- [start] content -->
        <p>Due to the recent appearance on <?php echo $campaignName; ?>, the Lecom website is temporarily unavailable. Please try again later.</p>
		<p class="rlink"><a href="<?php echo $this->getBaseUrl()?>" title="Lecom">Click here to visit the site again</a></p>
    <!-- [end] content -->
    </div>
<!-- [end] center -->