<?php if($this->getCollection()->getSize()): ?>

    <div class="clearfix gridOptions">

    <?php if($this->getLastPageNum()>1): ?>
    <div class="pagelist">
        
	   <ul class="num">
	   
       <?php if (!$this->isFirstPage()): ?>
	   <li>
            <div class="lftArw">
                <a class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>" href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo $this->__('Previous') ?>">
                   <?php echo $this->__('Previous Page') ?>
				   <img src="<?php echo $this->getSkinUrl('images/lftArw.gif') ?>" alt="<?php echo $this->__('Previous') ?>" class="v-middle" />
                </a>
            </div>
		</li>
        <?php endif;?>


        <?php if ($this->canShowFirst()): ?>
            <li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
        <?php endif;?>

        <?php if ($this->canShowPreviousJump()): ?>
            <li><a class="previous_jump" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
        <?php endif;?>

        <?php foreach ($this->getFramePages() as $_page): ?>
            <?php if ($this->isPageCurrent($_page)): ?>
                <li class="active"><?php echo $_page ?></li>
            <?php else: ?>
                <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
            <?php endif;?>
        <?php endforeach;?>


        <?php if ($this->canShowNextJump()): ?>
            <li><a class="next_jump" title="" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
        <?php endif;?>

        <?php if ($this->canShowLast()): ?>
          <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
        <?php endif;?>    
        
		
		<?php if (!$this->isLastPage()): ?>
		<li>
            <div class="rgtArw">
                <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo $this->__('Next') ?>">
					<img src="<?php echo $this->getSkinUrl('images/rgtArw.gif') ?>" alt="<?php echo $this->__('Next') ?>" class="v-middle" />
                    <?php echo $this->__('Next Page') ?>
                </a>
            </div>
		</li>
        <?php endif;?>
		</ul>
    </div>
    <?php endif; ?>

 
    </div>

<?php endif ?>
