<!-- Gift card html start-->
<h3><?php echo $this->__('E-Voucher Code') ?></h3>
	<div class="clear"></div>
	<div id="giftcard_balance_lookup"></div>
	<span id="gc-please-wait" class="please-wait" style="display:none;">
		<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
	</span>
	<form id="giftcard-form" action="<?php echo $this->getUrl('enterprise_giftcardaccount/cart/add') ?>" method="post">
		<input class="ck-promo-fld mar-none  fl" id="giftcard_code" name="giftcard_code" onblur="javascript:onBlurText(this,'Enter the e-voucher code');" onclick="javascript:onClickText(this,'Enter the e-voucher code');"/>
		<a href="" id="cart-e-voucher-add" class="button" onclick="validateEvoucher();"  value="<?php echo $this->__('Add') ?>"><?php echo $this->__('Add') ?></a>
		<div id="gvc-loading" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif'); ?>"></div>
		<br /><br />
		<div class="clear"></div>
		<div id="error_reg_gvc" class="sgn-error notification-msg fl" style="display: none;"> 
			<span class="fl" id="error-gvc">Please redeem your e-voucher code here.</span>
		</div>
	</form>
<script type="text/javascript">
jQuery('#cart-check-for-balance').css({
	position:'relative',
	left:'2px',
	top:'-14px'
	});
//<![CDATA[
var giftcardForm = new VarienForm('giftcard-form');
function checkGiftCardStatus()
{
	if (giftcardForm.validator && !giftcardForm.validator.validate()) {
		return false;
	}
	new Ajax.Updater(
		'giftcard_balance_lookup',
		'<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>',
		{
			onCreate: function() { $('gc-please-wait').show(); },
			onComplete: function() { $('gc-please-wait').hide(); },
			parameters : {giftcard_code : $('giftcard_code').value}
		}
	);
}

function validateEvoucher() {
	var gcval = jQuery("#giftcard_code").val();
	if(gcval == '' || gcval == 'Enter the e-voucher code'){
		jQuery("#error-gvc").show().addClass("error-msg-redtxt").html('Please enter valid e-voucher code.');
		return false;
	}
	else{
		jQuery("#gvc-loading").show();
		jQuery("#error_reg_gvc").hide();
		giftcardForm.submit();
	}									
}	

//]]>
</script>
<!-- Gift card html end-->
