 <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('customer/account/navigation.phtml')->toHtml(); ?>
 <div class="default_address acc-perdetail fs14 f-lato" style="float: left; width: 700px;">
     <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
        <div class="shipping_add">
            <?php
                    $sa = Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses);
                    $saType = $sa->getAddresstype();
            ?>
            <h3><?php echo $this->escapeHtml($saType) ?>&nbsp;</h3>
            <div class="edit_btn shRight"> <a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>">Edit</a></div>
            <div class="clear"></div>
            <p style="height: 136px;">
                    <?php echo $this->getAddressHtml($sa) ?>
            </p>
            <span class="defaultlink">Default Address</span>
        </div>
     <?php endif ?>
	<?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
			<?php 
				$i = 0;
				foreach($_pAddsses as $_address): 
					$j = ++$i % 2;
					
					if ($j == 0) {
						$cl = 'shipping_add';
					} else {
						$cl = 'biling_add';
					}
			?>
			
				<div class="<?php echo $cl; ?>">
					<h3><?php echo $this->escapeHtml($_address->getAddresstype()) ?>&nbsp;</h3>
					<div class="edit_btn"> <a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>">Edit</a></div>
					<div class="delete_btn"> <a href="#" onclick="return deleteAddress('<?php echo $_address->getId() ?>');">Delete</a></div>
					<div class="clear"></div>
					<p style="height: 136px;">
						<?php echo $this->getAddressHtml($_address) ?>
					</p>
                                        <span class="defaultlink"><a style="color: #FFF" href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>">SET AS Default</a></span>
				</div>
			<?php
				if ($j == 0 && 0) {
			?>
					<div class="clear"></div>
			<?php
				}
			?>
			<?php endforeach; ?>
	<?php endif ?>
                        <div class="shipping_add" onclick="location.href='<?php echo $this->getUrl('customer/address/new/') ?>';" style="cursor: pointer; background: url('<?php echo $this->getSkinUrl('images/add_address.png'); ?>') no-repeat scroll center center rgb(222, 219, 219);">
  
                        </div>
 </div>

<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
