
<div class="rewardssocial-widgets">
    <?php foreach ($this->getSortedChildren() as $name): ?>
        <?php $block = $this->getLayout()->getBlock($name) ?>
        <?php if (!$block): ?>
            <?php Mage::throwException(Mage::helper('core')->__('Invalid block: %s', $name)) ?>
        <?php endif ?>
        <?php if (!$block->getIsHidden()): ?>
            <?php echo $block->toHtml() ?>
        <?php endif; ?>
    <?php endforeach ?>

    <?php echo $this->getPointsNotificationBlock()->toHtml() ?>
</div>
