<?php $cnt = count($this->getSidebarTestimonials()); ?>
<?php if($cnt > 0 ): ?>
<div class="block block-testimonials">
	<div class="block-title">
        <strong><span><?php echo $this->__('Testimonials') ?></span></strong>
    </div>
	<div class="block-content">


		<div id="carousel-wrapper">
			<div id="carousel-content">		
			<?php foreach ($this->getSidebarTestimonials() as $item): ?>                  
			<div class="slide">
				<p><?php echo '&ldquo;'.$item->getContent().'&rdquo;'; ?></p>
				<div class="name"><?php   echo $item->getName(); ?></div>
				<span class="url"><a href="http://<?php echo $item->getUrl(); ?>"><?php echo $item->getUrl(); ?></a></span>
			</div>  
			<?php endforeach;  ?> 
			</div>
		</div>
		<script type="text/javascript">
			new Carousel('carousel-wrapper', $$('#carousel-content .slide'), $$('a.carousel-control', 'a.carousel-jumper'), {auto:true, frequency :5, duration: 1, circular: true, effect: 'fade' });
		</script>
		<div style="float:right;"><a href="<?php echo $this->getUrl('testimonials'); ?>" title="<?php echo $this->__('View All Testimonials') ?>"><?php echo $this->__('View All Testimonials') ?></a></div>		
	</div>
</div>
<div style="clear:both;"></div>
<?php endif; ?>
