<?php
if ($product = Mage::registry('current_product')) {
$categories = $product->getCategoryCollection()->load();

if($categories) {
foreach ($categories as $category)
{
if($category) {
$category = Mage::getModel('catalog/category')->load($category->getId());
break;
}
}
}
$lastCrumbName = $product->getName();
$lastCategoryAdjust = 0;
}
else {
if($category = Mage::registry('current_category')) {
$lastCrumbName = $category->getName();
}
$lastCategoryAdjust = 1;
}

if($category) {
if($path = $category->getPath()) {
$path = explode('/', $path);
$crumbs = array('home' => array('label' => 'Home',
'title' => 'Home',
'link' => Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB),
'first' => true,
'last' => false
));
for($i = 2; $i < count($path) - $lastCategoryAdjust; $i++) {
$cur_category = Mage::getModel('catalog/category')->load($path[$i]);
if($cur_category && $cur_category->getIsActive()) {
$crumbs['category' . $path[$i]] = array('label' => $cur_category->getName(),
'title' => $cur_category->getName(),
'link' => $cur_category->getUrl(),
'first' => false,
'last' => false
);
}
}
$crumbs['current'] = array('label' => $lastCrumbName,
'title' => '',
'link' => '',
'first' => false,
'last' => true
);
}
}
?>
<?php $i=1;?>
<?php if($crumbs && is_array($crumbs)): ?>
<ul xmlns:v="http://rdf.data-vocabulary.org/#" itemscope itemtype="http://schema.org/BreadcrumbList">
<?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>

<?php if($_crumbInfo['link']): ?>
	<li class="<?php echo $_crumbName ?>" typeof="v:Breadcrumb" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem">
		<a itemprop="item" href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>" rel="v:url" property="v:title"><span itemprop="name"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></span></a><meta itemprop="position" content="<?php echo $i; ?>" />
	</li>
<?php elseif($_crumbInfo['last']): ?>
	<li class="<?php echo $_crumbName ?>" typeof="v:Breadcrumb">
		<?php echo $this->htmlEscape($_crumbInfo['label']) ?>
	</li>	
<?php else: ?>
	<li class="<?php echo $_crumbName ?>" typeof="v:Breadcrumb">
		<span rel="v:child" property="v:title"><?php echo $this->htmlEscape($_crumbInfo['label']) . ' for sale' ?></span>
	</li>	
<?php endif;   $i++;?>
<?php if(!$_crumbInfo['last']): ?>
<?php endif; ?>
</li>
<?php endforeach; ?>
</ul>
<?php endif; ?>