<?php
if ($product = Mage::registry('current_product')) {
$categories = $product->getCategoryCollection()->load();

if($categories) {
foreach ($categories as $category)
{
if($category) {
$category = Mage::getModel('catalog/category')->load($category->getId());
break;
}
}
}
$lastCrumbName = $product->getName();
$lastCategoryAdjust = 0;
}
else {
if($category = Mage::registry('current_category')) {
$lastCrumbName = $category->getName();
}
$lastCategoryAdjust = 1;
}

if($category) {
if($path = $category->getPath()) {
$path = explode('/', $path);
$crumbs = array('home' => array('label' => 'Home',
'title' => 'Home',
'link' => Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB),
'first' => true,
'last' => false
));
for($i = 2; $i < count($path) - $lastCategoryAdjust; $i++) {
$cur_category = Mage::getModel('catalog/category')->load($path[$i]);
if($cur_category && $cur_category->getIsActive()) {
$crumbs['category' . $path[$i]] = array('label' => $cur_category->getName(),
'title' => $cur_category->getName(),
'link' => $cur_category->getUrl(),
'first' => false,
'last' => false
);
}
}
$crumbs['current'] = array('label' => $lastCrumbName,
'title' => '',
'link' => '',
'first' => false,
'last' => true
);
}
}
?>
<?php if($crumbs && is_array($crumbs)): ?>
<div class="bredcrum">
	<ul xmlns:v="http://rdf.data-vocabulary.org/#">
		<?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
	<li class="<?php echo $_crumbName ?>" typeof="v:Breadcrumb">
		<?php if($_crumbInfo['link']): ?>
	<a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>" rel="v:url" property="v:title"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></a>
		<?php elseif($_crumbInfo['last']): ?>
	<strong><?php echo $this->htmlEscape($_crumbInfo['label']) ?></strong>
		<?php else: ?>
	<span rel="v:child" property="v:title"><strong><?php echo $this->htmlEscape($_crumbInfo['label']) . ' for sale' ?></strong></span>
		<?php endif; ?>
	<?php if(!$_crumbInfo['last']): ?>
	
	<?php endif; ?>
	</li>
	<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>