<div id="topoffers">
<div class="container"><h3>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('aswan-top-offer-banner')->toHtml(); ?></h3>
 <h4><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('aswan-top-customer-care-number')->toHtml(); ?></h4></div>
</div>
<div id="quickbag">
<?php echo $this->getChildHtml('topCart') ?>
<div class="bagsummary">
<span id="closebag"></span>
<h3>Shopping Bag</h3>
<p><?php $cartQty = Mage::helper('checkout/cart')->getSummaryCount();
   if($cartQty > 0)           {
	echo $cartQty.' Items';
   }
   else {
	 echo "0 Item";
   }
 ?></p>
<a href="<?php echo $this->getUrl('checkout/cart'); ?>" class="viewbag">View Bag</a>
</div>
</div>
<div id="logo"><a href="<?php echo Mage::getBaseUrl();?>"><img src="<?php echo $this->getSkinUrl().Mage::getStoreConfig('design/header/logo_src');?>" /></a></div>
<div id="mobilelogo"><a href="<?php echo Mage::getBaseUrl();?>"><img src="<?php echo $this->getSkinUrl('images/mobile-logo.jpg');?>" /></a></div>
<!-- Desktop top menu Start -->
<div id="topmenu">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('aswan-topmenu')->toHtml(); ?>
</div>
<!-- End desktop top menu Start -->
<div id="topright">
<ul>
<li id="mobilemenu"><span class="lines"></span> <span class="lable">Menu</span></li>

<?php 
$customerinfo = Mage::getSingleton('customer/session');
if($customerinfo->isLoggedIn()){
	$customer = Mage::getSingleton('customer/session')->getCustomer();
	
?>
<li class="welcome">Welcome &nbsp;<?php echo $customer->getFirstname();?>&nbsp;!</li>
<?php 
}
?>

<li class="search"><span class="icon"></span> <span class="lable">Search</span></li>

<?php 
$customerinfo = Mage::getSingleton('customer/session');
if($customerinfo->isLoggedIn()){
	$customer = Mage::getSingleton('customer/session')->getCustomer();
	
?>
<li class="myaccount">
<a class="accountdrop" href="#"><span class="icon"></span><span class="lable">Sign in</span></a>
	<ol class="accountlinks">
		<li><a href="<?php echo $this->getUrl('customer/account/');?>">My account</a></li>
		<li><a href="<?php //echo $this->getUrl('customer/account/orders');?>">Track Orders</a></li>
		<li><a href="<?php echo $this->getUrl('customer/account/wallet');?>">My wallet</a></li>
		<li><a href="<?php echo $this->getUrl('customer/account/logout');?>" id="gtm-logout" class="tt-u fs12 c-fff td-n pl10 gtm-track">Logout</a></li>
	</ol>
</li>
<?php 
}
else{
?>
<li class="myaccount"><a class="fancybox" href="#loginpopup"><span class="icon"></span> <span class="lable">Sign in</span></a></li>
<?php 
}
?>

<li class="myaccount" id="mobilelogin"><a href="login-register.html"><span class="icon"></span> <span class="lable">Sign in</span></a></li>
<li class="cartbox" id="showbag"><span class="lable">Bag</span> <span class="icon"></span></li>
<li class="cartbox" id="mobilecart"><a href="cart.html"><span class="lable">Bag</span> <span class="icon"></span></a></li>
</ul>
</div>
<div class="topsearch">
 <?php echo $this->getChildHtml('topSearch') ?>
</div>
<!-- Mobile Menu start -->
<div id="mobnavigation">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('aswan-mobile-menu')->toHtml(); ?>
</div>
<!-- Mobile Menu End -->
