<?php
// source & campaign start
$__utmzscVal = Mage::helper('common')->checkUtmzscCookies();
if(!empty($__utmzscVal)) {
?>
<script>setCookie('__utmzsc','<?php echo $__utmzscVal ?>',30);</script>
<?php
}
// source & campaign end
?>
<?php $customerinfo = Mage::getSingleton('customer/session');?>
<script type="application/ld+json">// <![CDATA[
{	
  "@context" : "http://schema.org",
  "@type" : "Organization",
  "url" : "<?php echo Mage::getBaseUrl();?>",
  "logo" : "<?php echo $this->getSkinUrl();?>images/logo.png",
  "contactPoint" : [{
    "@type" : "ContactPoint",
    "telephone" : "850-648-4200",
    "contactType" : "customer service",
    "contactOption" : "TollFree"
  }],
}
// ]]></script>
<div id="topoffers">
<div class="container"><h3>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('aswan-top-offer-banner')->toHtml(); ?></h3>
 <h4 itemprop="contactPoint" itemtype="http://schema.org/ContactPoint"><p itemprop="telephone"/>850-648-4200 (Mon - Sat 10 am - 7 pm)</p><?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('aswan-top-customer-care-number')->toHtml(); ?></h4></div>
</div>
<div id="quickbag">
<?php echo $this->getChildHtml('topCart') ?>
<div class="bagsummary">
<span id="closebag"></span>
<h3>Shopping Bag</h3>
<p><?php $cartQty = Mage::helper('checkout/cart')->getSummaryCount();
   if($cartQty > 0) {
	echo $cartQty.' Items';
   }
   else {
	 echo "0 Item";
   }
 ?></p>
<a href="<?php echo $this->getUrl('checkout/cart'); ?>" class="viewbag">View Bag</a>
</div>
</div>
<div id="logo"><a href="<?php echo Mage::getBaseUrl();?>"><img src="<?php echo $this->getSkinUrl().Mage::getStoreConfig('design/header/logo_src');?>" /></a></div>
<div id="mobilelogo"><a href="<?php echo Mage::getBaseUrl();?>"><img src="<?php echo $this->getSkinUrl('images/mobile-logo.png');?>" /></a></div>
<!-- Desktop top menu Start -->
<div id="topmenu">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('aswan-topmenu')->toHtml(); ?>
</div>
<!-- End desktop top menu Start -->
<div id="topright">
<ul>
<li id="mobilemenu"><span class="lines"></span> <span class="lable">Menu</span></li>

<?php 

if($customerinfo->isLoggedIn()){
	$customer = Mage::getSingleton('customer/session')->getCustomer();
	
?>
<li class="welcome"><?php echo $this->getWelcome();?></li>
<?php 
}
else{
?>
<li class="welcome">Welcome Guest !</li>
<?php	
}
?>

<li class="search"><span class="icon"></span> <span class="lable">Search</span></li>
<?php echo $this->getChildHtml('topLinks'); ?>
<li class="cartbox" id="showbag">
<?php  if($cartQty > 0) {?>
	<strong id="cartcount"><?php echo $cartQty;?></strong>
  <?php } else { ?>
  	 <strong id="cartcount">0</strong>
  <?php }
   
 ?>
<span class="lable">Bag</span> <span class="icon"></span></li>
<li class="cartbox" id="mobilecart"><a href="<?php echo Mage::getBaseUrl();?>checkout/cart/"><span class="lable">Bag</span> <span class="icon">
<?php  if($cartQty > 0) {?>
  <strong id="mobicount"><?php echo $cartQty;?></strong>
  <?php } else { ?>
     <strong id="mobicount">0</strong>
  <?php }
   
 ?>
</span></a></li>
</ul>
</div>
<div class="topsearch">
 <?php echo $this->getChildHtml('topSearch') ?>
</div>
<!-- Mobile Menu start -->
<div id="mobnavigation">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('aswan-mobile-menu')->toHtml(); ?>
</div>
<!-- Mobile Menu End -->
