<h3>My billing address</h3>
<ul>
<?php
$formErrors = $this->getParentBlock()->formErrors;
$formErrors = (!empty($formErrors['billing_errors'])) ? $formErrors['billing_errors'] : array();
$helper = Mage::helper('onestepcheckout/checkout');
$dataHelper = Mage::helper('onestepcheckout');

$_name = trim($this->getQuote()->getBillingAddress()->getFirstname().' '.$this->getQuote()->getBillingAddress()->getLastname());
    $billingFields['firstname'] = '
        <li class="input-box input-firstname'.((in_array('firstname', $formErrors)) ? ' input-error' : '').'">
            <label class="mar-t10">'.$this->__('Full Name').'*</label>
            <input class="required-entry cklargefield-email validate-alpha-with-spaces" type="text" name="billing[firstname]" id="billing:firstname" value="'.$dataHelper->clearDash($_name).'" />
        </li>';
?>

<?php if(!$this->isCustomerLoggedIn()): ?>
    <?php $billingFields['email'] = '
        <li class="input-box input-email'.((in_array('email', $formErrors)) ? ' input-error' : '').'">
            <span class="mar-t10">'.$this->__('E-mail').'*</span>
            <input type="text" name="billing[email]" id="billing:email" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getEmail())).'" title="'.$this->__('Email Address') .'" class="validate-email required-entry cklargefield-email cutomer-email" />
        </li>';
    ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_telephone']):?>
    <?php $billingFields['telephone'] = '
        <li class="input-box input-telephone'.((in_array('telephone', $formErrors)) ? ' input-error' : '').'">
            <label class="mar-t10">'.$this->__('Phone').' *</label>
            <input type="text" name="billing[telephone]" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getTelephone())).'" title="'.$this->__('Telephone').'" class="cklargefield-email validate-mobile required-entry" id="billing:telephone" />
        </li>';
    ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_address']):?>
    <?php if(Mage::getStoreConfig('onestepcheckout/exclude_fields/enable_address_fields')):?>
        <?php
        $addressFields = '';
            for ($_i=1, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++){
                    $addressFields .= '<li class="input-box input-address-short'.((in_array('address', $formErrors)) ? ' input-error' : '').'">
                    <label class="mar-t10">'.$this->__('Address Line'.$_i);
					if($_i<$_n){
						$addressFields .= '*</label>';
						$addressFields .= '<input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street][]" id="billing:street'.$_i.'" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getStreet($_i))).'" maxlength="125" class="required-entry cklargefield-email onestepcheckout-address-line validate-address" />';
					}else{
						$addressFields .= '</label>';
						$addressFields .= '<input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street][]" id="billing:street'.$_i.'" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getStreet($_i))).'" maxlength="125" class="cklargefield-email onestepcheckout-address-line validate-address" />';
					}
                    $addressFields .= '</li>';
            }
            $billingFields['street'] = $addressFields;
        ?>
    <?php else:?>
        <?php
        $addressFields = '';
            for ($_i=1, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++){

                    $addressFields .= '<input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street][]" id="billing:street'.$_i.'" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getStreet($_i))).'" maxlength="125" class="'.(($_i == 1)? 'required-entry ' : '').'input-text onestepcheckout-address-line validate-address" />';
                    $addressFields .= (($_i != $this->helper('customer/address')->getStreetLines()) ? '<br/>': '');
            }
            $billingFields['street'] = '
                <div class="input-box input-address validate-street'.((in_array('address', $formErrors)) ? ' input-error' : '').'">
                    <span class="mar-t10">'.$this->__('Address').'*</span>
                    '.$addressFields.'
                </div>';
        ?>
    <?php endif; ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_country_id']):?>
<?php
$billingFields['country_id'] = '<div class="clear"></div>
                  <label class="mar-t10">'.$this->__('Country').'*</label>
    <div class="cksmallfield-mob-wrap input-box input-country'.((in_array('country', $formErrors)) ? ' input-error' : '').'">
            '.$this->getCountryHtmlSelect('billing').'
    </div>';
?>
<?php else: ?>
<?php $billingFields['country_id'] = '
    <input type="hidden" name="billing[country_id]" id="billing:country_id" value="'.$this->settings['default_country'].'" />';
?>
<?php endif; ?>
<?php if(!$this->settings['exclude_region']): ?>
    <?php $billingFields['region_id'] = '<div class="clear"></div><label class="mar-t10">'.$this->__('State').'*</label>
        <div class="cksmallfield-mob-wrap input-box input-region'.((in_array('region', $formErrors)) ? ' input-error' : '').'">
            <select id="billing:region_id" name="billing[region_id]" title="'.$this->__('State/Province').'" class="cksmallfield-mob pad-none validate-select state-select" style="display:none">
                <option value="">'.$this->__('Please select region, state or province').'</option>
            </select>
            <script type="text/javascript">
                $("billing:region_id").setAttribute("defaultValue",  "'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getRegionId()).'");
            </script>
            <input type="text" id="billing:region" name="billing[region]" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getRegion())).'" title="'.$this->__('State/Province').'" class="required-entry input-text state-input" style="display:none" />
        </div>';
    ?>
<?php endif; ?>
<?php if(!$this->settings['exclude_city']):?>
    <?php $billingFields['city'] = '
        <li><div class="fl input-box input-city'.((in_array('city', $formErrors)) ? ' input-error' : '').'">
            <label class="mar-t10 mar-l10">'.$this->__('City').'*</label>
            <input type="text" name="billing[city]" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getCity())).'" title="'.$this->__('City').'" class="required-entry cklargefield-email" id="billing:city" />
        </div></li></div>';
    ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_zip']): ?>
    <?php $billingFields['postcode'] = '<div class="st-field-wrapp fl">
        <li class="ck-boxWrapp fl input-box input-postcode'.((in_array('postcode', $formErrors)) ? ' input-error' : '').'" >
             <label class="mar-t10">'.$this->__('Pin Code').'*</label>
            <input type="text" style="width:150px" title="'.$this->__('Zip/Postal Code').'" name="billing[postcode]" maxlength="6" id="billing:postcode" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getPostcode())).'" class="billing-zip vrequired-entry validate-number cklargefield-email mb5 fl" /><div class="reg-success hide" id="bill_pincode_search"><input type="button" value="GO"></div>
        </li>';
    ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_company']): ?>
    <?php $billingFields['company'] = '
        <div class="input-box input-company'.((in_array('company', $formErrors)) ? ' input-error' : '').'">
            <label for="billing:company">'.$this->__('Company').'</label>
            <input type="text" name="billing[company]" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getCompany())).'" title="'.$this->__('Company').'" class="input-text" id="billing:company" />
        </div>';
    ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_fax']): ?>
    <?php $billingFields['fax'] = '
        <div class="input-box input-fax'.((in_array('fax', $formErrors)) ? ' input-error' : '').'">
            <span class="mar-t10">'.$this->__('Fax').'*</span>
            <input type="text" name="billing[fax]" value="'.$this->htmlEscape($dataHelper->clearDash($this->getQuote()->getBillingAddress()->getFax())).'" title="'.$this->__('Fax').'" class="cklargefield-email" id="billing:fax" />
        </div>';
    ?>
<?php endif; ?>

<?php
    $_taxvat = false;
    try {
        if(Mage::getStoreConfig('onestepcheckout/exclude_fields/enable_pillwaxeuvat_support')){
            $_taxvat = $this->getLayout()->createBlock('euvat/widget_taxvat');
        }
    } catch (Exception $e) {
    }
    if(!is_object($_taxvat)){
        $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat');
    }
?>
<?php if(is_object($_taxvat) && $_taxvat->isEnabled()): ?>
    <?php $billingFields['taxvat'] =
            $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())
                ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml();
    ?>
<?php endif; ?>

<?php
	/* DOB removed from Checkout as per BSC */
    try {
		$dobvalue = $this->getQuote()->getCustomerDob();
		if(!isset($dobvalue)){
			$_dob = $this->getLayout()->createBlock('customer/widget_dob');
		}else{
			$_dob = false;
		}
    } catch (Exception $e) {
        $_dob = false;
    }
?>
<?php
/* Gender removed
    try {
        $_gender = $this->getLayout()->createBlock('customer/widget_gender');
    } catch (Exception $e) {
        $_gender = false;
    } */
?>

<?php if (is_object($_dob) && $_dob->isEnabled()): ?>
    <?php $billingFields['dob'] = '
        <div class="field" style="display:none;"><table>
            '.$_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'
        </table></div>';
    ?>
<?php endif; ?>
<?php /* if (is_object($_gender) && $_gender->isEnabled()): ?>
    <?php $billingFields['gender'] = '
        <div class="field">
            '.$_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'
        </div>';
    ?>
<?php endif */ ?>
<?php if(!$this->isCustomerLoggedIn() && $helper->showCreateAccount()): ?>
    <?php $billingFields['create_account'] = '
        <div class="input-box">
            <input id="id_create_account" type="checkbox" name="create_account" value="1" '.((isset($_POST['create_account']) && $_POST['create_account'] == '1') ? ' checked="checked"' : '').' />
            <label for="id_create_account">'.$this->__('Create an account for later use').'</label>
        </div>

        <script>
        document.observe("dom:loaded", function() {
            $("id_create_account").observe("click", function(e) {
                var element = e.element();
                if(element.checked) {
                    $("onestepcheckout-li-password").show();
                }
                else    {
                    $("onestepcheckout-li-password").hide();
                }
            });
        });
        </script>';
    ?>
<?php endif; ?>
<?php if($helper->showPasswords() && !$this->isCustomerLoggedIn()): ?>
    <?php
        //id="onestepcheckout-li-password"
        $billingFields['password'] = '
        <li id="onestepcheckout-li-password" '.(($helper->hidePasswords()) ? 'style="display: none;"':'').'>
            <div class="input-box input-password'.((in_array('password', $formErrors)) ? ' input-error' : '').'">
                <label for="billing:customer_password">'.$this->__('Password').'</label><br/>
                <input type="password" class="input-text required-entry validate-password" value="'.((isset($_POST['billing']['customer_password'])) ? $_POST['billing']['customer_password'] : '').'" title="Password" id="billing:customer_password" name="billing[customer_password]"/>
            </div>
            <div class="input-box input-password'.((in_array('confirm_password', $formErrors)) ? ' input-error' : '').'">
                <label for="billing:confirm_password">'.$this->__('Confirm password').'</label><br/>
                <input type="password" class="input-text required-entry validate-cpassword" value="'.((isset($_POST['billing']['confirm_password'])) ? $_POST['billing']['confirm_password'] : '').'" id="billing:confirm_password" title="Confirm Password" name="billing[confirm_password]"/>
            </div>
        </li>';
    ?>
<?php endif; ?>
<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
    <?php $billingFields['save_in_address_book'] = '<input type="hidden" name="billing[save_in_address_book]" class="billing_save_address" value="0" />';
    ?>
<?php else:?>
    <?php $billingFields['save_in_address_book'] = '
    <input type="hidden" name="billing[save_in_address_book]" value="1" />';
    ?>
<?php endif; ?>

<?php $billingFields = $this->getBillingFieldsOrder($billingFields);?>
<?php foreach($billingFields as $key => $value):?>
    <?php if(!empty($value['has_li'])):?>
        <?php echo implode('',$value['fields']);?>
    <?php else:?>
        <?php echo implode('',$value['fields']);?>
    <?php endif;?>
<?php endforeach;?>
</ul>
<script type="text/javascript">
jQuery(document).ready(function(){
	if(jQuery(".state-select").length > 0){
		jQuery(".state-select").addClass("validate-select");
	}
	if(jQuery("#billing_address .dob-day select").length > 0){
		 jQuery("#billing_address .dob-day select").val('01');
	}
	if(jQuery("#billing_address .dob-month select").length > 0){
		 jQuery("#billing_address .dob-month select").val('01');
	}
	if(jQuery("#billing_address .dob-year select").length > 0){
		 jQuery("#billing_address .dob-year select").val('1902');
	}
	if(jQuery("#billing_address .dob-full input").length > 0){
		 jQuery("#billing_address .dob-full input").val('01/01/1902');
	}
});
</script>
