<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="pagename"><h2><?php echo $this->__('My Shopping Bag');?></h2>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div id="cartarea">
	<div id="cartleft">
		 
		<?php echo $this->getChildHtml('form_before') ?>
		<form id="checkout-form" action="<?php echo $this->getUrl('checkout/cart/updatePost');?>" method="post">
		<?php foreach($this->getItems() as $_item): ?>
				<?php echo $this->getItemHtml($_item); ?>
		 <?php endforeach; ?>
		</form>
	</div>
<div id="cartright">
	<div class="stickycol1">
		<div class="summryboxs">
			<h3><?php echo $this->__('Order Summary') ?></h3>
				<?php echo $this->getChildHtml('totals');?>
		</div>
		 <?php //echo $this->getChildHtml('shopping.cart.table.after'); ?>
		 <?php if(!$this->hasError()): ?>
        <?php foreach ($this->getMethods('methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <div class="buttons"><?php echo $methodHtml; ?></div>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php endif; ?>
        
		<div class="couponboxs">
			 <?php echo $this->getChildHtml('coupon'); ?>
		</div>
		<div class="couponboxs">
			<?php echo $this->getChildHtml('giftcards');?>
		</div>
	</div>
	</div>
	
<div class="clearfloat"></div>
</div>
</div>
<script>
function updatecart(obj){
	
	jQuery("#checkout-form").submit();
}
</script>



