<div id="error_message"></div>
<div class="page_title p30">Select Message for Invite:</div>
<form action="<?php echo Mage::getBaseUrl() . 'socialapi/index/sendFacebook/' ?>" method="post">
    <div class="messageBox">
        <h3>Select Message:</h3>
        <select name="facebook_message_select" class="select" onchange="javascript:changeMessage(this);" style="width:250px;">
            <option value="1"><?php echo $this->limit_words(Mage::getStoreConfig('socialapi/facebook/invitemsg_1'), 10); ?></option>
            <option value="2"><?php echo $this->limit_words(Mage::getStoreConfig('socialapi/facebook/invitemsg_2'), 10); ?></option>
            <option value="3"><?php echo $this->limit_words(Mage::getStoreConfig('socialapi/facebook/invitemsg_3'), 10); ?></option>
            <option value="4"><?php echo $this->limit_words(Mage::getStoreConfig('socialapi/facebook/invitemsg_4'), 10); ?></option>
            <option value="5"><?php echo $this->limit_words(Mage::getStoreConfig('socialapi/facebook/invitemsg_5'), 10); ?></option>
        </select>

        <input type="hidden" name="invitemsg_1" value="<?php echo Mage::getStoreConfig('socialapi/facebook/invitemsg_1'); ?>" id="invitemsg_1" />
        <input type="hidden" name="invitemsg_2" value="<?php echo Mage::getStoreConfig('socialapi/facebook/invitemsg_2'); ?>" id="invitemsg_2" />
        <input type="hidden" name="invitemsg_3" value="<?php echo Mage::getStoreConfig('socialapi/facebook/invitemsg_3'); ?>" id="invitemsg_3" />
        <input type="hidden" name="invitemsg_4" value="<?php echo Mage::getStoreConfig('socialapi/facebook/invitemsg_4'); ?>" id="invitemsg_4" />
        <input type="hidden" name="invitemsg_5" value="<?php echo Mage::getStoreConfig('socialapi/facebook/invitemsg_5'); ?>" id="invitemsg_5" />

        <h3>Message Preview:</h3>
        <textarea readonly="true" name="facebook_message" cols="" rows="" id="facebook_message"><?php echo Mage::getStoreConfig('socialapi/facebook/invitemsg_1'); ?></textarea>
        <br clear="all"/>
        <button type="submit" title="<?php echo $this->__('Send Invite') ?>" class="button invitesend"><?php echo $this->__('Send Invite') ?></button>
    </div>
</form>

<script type="text/javascript">
    function changeMessage(myselect){
        var selectval = jQuery(myselect).val();
        var message = jQuery("#invitemsg_"+selectval).val();
        jQuery("#facebook_message").html(message);
    }

    jQuery(document).ready(function(){	
        jQuery(function(){jQuery("select").uniform();});
    });
</script>
<style type="text/css">
    div.selector span { width: 210px; }
</style>
