<div id="error_message"></div>
<?php $yahoo_contacts = $this->yahoo(); ?>
<div class="page_title p30">Select Contacts to Send Invite:</div>
<?php if (!empty($yahoo_contacts)) {
 ?>
    <form action="<?php echo $this->getUrl('*/*/sendYahoo') ?>" method="post" onsubmit="return validateForm()">
        <div class="addrssBook">
        <?php
        foreach ($yahoo_contacts as $id => $yahoo_contact) {
            if (!empty($yahoo_contact['email'])) {
                $name = empty($yahoo_contact['name']) ? $yahoo_contact['email'] : $yahoo_contact['name'];
                $name = $this->limit_words($name, 10);
        ?>
                <span><input type="checkbox" name="yahoo_contact[<?php echo $name; ?>]" value="<?php echo $yahoo_contact['email']; ?>" class="social-contact" />
                    <label><?php echo $name; ?></label>
                </span>
<?php }
        } ?>
    </div>

    <div class="messageBox">
        
        <h3>Select Message:</h3>
        <select name="yahoo_message_select" class="select" onchange="javascript:changeMessage(this);" style="width:250px;">
            <option value="1"><?php echo $this->limit_words(Mage::getStoreConfig('socialapi/yahoo/invitemsg_1'), 10); ?></option>
            <option value="2"><?php echo $this->limit_words(Mage::getStoreConfig('socialapi/yahoo/invitemsg_2'), 10); ?></option>
            <option value="3"><?php echo $this->limit_words(Mage::getStoreConfig('socialapi/yahoo/invitemsg_3'), 10); ?></option>
            <option value="4"><?php echo $this->limit_words(Mage::getStoreConfig('socialapi/yahoo/invitemsg_4'), 10); ?></option>
            <option value="5"><?php echo $this->limit_words(Mage::getStoreConfig('socialapi/yahoo/invitemsg_5'), 10); ?></option>
        </select>

        <input type="hidden" name="invitemsg_1" value="<?php echo Mage::getStoreConfig('socialapi/yahoo/invitemsg_1'); ?>" id="invitemsg_1" />
        <input type="hidden" name="invitemsg_2" value="<?php echo Mage::getStoreConfig('socialapi/yahoo/invitemsg_2'); ?>" id="invitemsg_2" />
        <input type="hidden" name="invitemsg_3" value="<?php echo Mage::getStoreConfig('socialapi/yahoo/invitemsg_3'); ?>" id="invitemsg_3" />
        <input type="hidden" name="invitemsg_4" value="<?php echo Mage::getStoreConfig('socialapi/yahoo/invitemsg_4'); ?>" id="invitemsg_4" />
        <input type="hidden" name="invitemsg_5" value="<?php echo Mage::getStoreConfig('socialapi/yahoo/invitemsg_5'); ?>" id="invitemsg_5" />

        <h3>Message:</h3>
        <textarea name="yahoo_message" id="yahoo_message" cols="" rows="" readonly="true"><?php echo Mage::getStoreConfig('socialapi/yahoo/invitemsg_1'); ?></textarea>
        <br clear="all"/>
        <button type="submit" title="<?php echo $this->__('Send Invite') ?>" class="button invitesend"><?php echo $this->__('Send Invite') ?></button>
            </div>
        </form>
<?php } else { ?>
        <p class="error-msg">No contacts found</p>
<?php } ?>

<script type="text/javascript">   
   
    function validateForm(){

        var allChecked = true;
        var length = jQuery("input.social-contact:checked").length;
        if(length <= 0){
            allChecked = false;
            jQuery("#error_message").html('<p class="error-msg">Please select a contact to send invite to.</p>');
        }

        return allChecked;
    }

    function changeMessage(myselect){
        var selectval = jQuery(myselect).val();
        var message = jQuery("#invitemsg_"+selectval).val();
        jQuery("#yahoo_message").html(message);
    }

    function Resize(width, height)
    {

        var availWidth = window.screen.availWidth;
        var availHeight = window.screen.availHeight;

        var top = (availHeight - height) / 2;
        var left = (availWidth - width) / 2;

        if (window.dialogHeight)
        {
            window.dialogHeight = height + 'px';
            window.dialogWidth = width + 'px';
            window.dialogLeft = left;
            window.dialogTop = top;
        }
        else
        {
            var _win;
            if(window.parent) _win = window.parent;
            else _win = window;
            _win.resizeTo(width, height);
            //_win.moveTo(left, top);
        }
    }

    jQuery(document).ready(function(){
        jQuery(function(){jQuery("select").uniform();});
        Resize(1000, 560);
    });

</script>
<style type="text/css">
    div.selector span { width: 210px; }
</style>