<script type="text/javascript">    
    jQuery(function(){jQuery("#itemrightQickview select,#itemrightQickview input[type=checkbox],#itemrightQickview input[type=radio]").uniform();});
</script>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
	$requestUrl=$this->getRequest()->getRequestString();
	$_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product);
?>
<?php
    if ($_product->getTypeId() == "configurable") {
        $associated_products = $_product->loadByAttribute('sku', $_product->getSku())->getTypeInstance()->getUsedProducts();
        foreach ($associated_products as $assoc){
			$moreImg = array();
			$assocImg = Mage::getModel('catalog/product')->load($assoc->getId())->getMediaGalleryImages();
			$img = (string)$this->helper('catalog/image')->init($assoc, 'image', $assoc->image)->resize(300,300);
			foreach($assocImg as $key=>$value){
				$moreImg[] = $value->getData();
			} 
            $dados[$assoc->getId()]['main_image'] = $img;
			$dados[$assoc->getId()]['more_image'] = $moreImg;
			unset($img);
			unset($moreImg);
		}
    }else{
		$dados[] =  "''";
	}
	$jsonString = json_encode($dados);
    ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
	var assocIMG = <?php echo $jsonString; ?> // Added  - Removed { here, causes issues with other scripts when not working with a configurable product.
</script>
<div id="itemdetails" class="QuickPopViewBox1">    
    <?php echo $this->getChildHtml('global_messages') ?>    
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="" id="icart-product-view">
    <form action="<?php if (strpos($requestUrl, '/edit/')) echo $this->getUrl('checkout/icart/edit', array('id' => $this->getRequest()->getParam('id'))); else echo Mage::helper('icart')->getAddUrl($_product) ?>" method="post" id="product_addtocart_form_icart"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?> onsubmit="productAddToCartFormIcart.submit(this);">
    <div id="quickview">
		<div class="no-display">
			<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
			<input type="hidden" name="related_product" id="related-products-field" value="" />
		</div>
		<div class="quickleft"><?php echo $this->getChildHtml('media') ?></div>
		<div class="quickright" id="itemrightQickview">
			<h3><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h3>

            <h4> <?php $price = Mage::helper('core')->currency($_product->getPrice(),true,false);?>
    <?php $specialPrice = Mage::helper('core')->currency($_product->getFinalPrice(),true,false);?>
             <span class="old-price"><?php if($price >$specialPrice) { echo $price;}?></span>
             <span class="new-price"><?php if($price ==$specialPrice) { echo $price;} else { echo $specialPrice;}?></span>
</h4>

<p><?php echo $_product->getDescription();?></p>

<!-- Click offer start -->
				<?php
	$_price = Mage::helper('core')->currency($_product->getPrice(),false,false);   
	$_specialPrice = Mage::helper('core')->currency($_product
					->getFinalPrice(),false,false);
		if ($_specialPrice == $_price): 
		$pdp_coupon_code = Mage::helper('common')->getCouponCodeByPrice($_price);
		$discounted_price = Mage::helper('common')->getCouponDiscountByCode($pdp_coupon_code, $_price);
		else: 
        $pdp_coupon_code = Mage::helper('common')->getCouponCodeByPrice($_specialPrice);
         $discounted_price = Mage::helper('common')->getCouponDiscountByCode($pdp_coupon_code, $_specialPrice);
         ?>
<?php endif; ?>
<?php if(!empty($pdp_coupon_code)) { ?>
<div class="clickoffer">
<h4>Click For Offer</h4>
<div class="offerdetail">
<div class="offerclose"></div>
Shop this product for <?php echo Mage::helper('core')->currency($discounted_price, true, true) ?> by applying coupon<span><?php echo $pdp_coupon_code; ?></span>in your cart. 
</div>
</div>
<?php } ?>
<!-- click offer end -->
            <div class="Q-price-tag">
                <div class="Q-price-value-cont">
                	<span class="old-price-tag"><?php echo $this->getChildHtml('customprice') ?></span>
                </div>
            </div>
			<div class="chosesizeboxWrapp chosesizeboxWrappnew productswaches">
<?php if ($_product->isSaleable() && $this->hasOptions() && $this->getChildChildHtml('container2')): ?>
<?php echo $this->getChildChildHtml('container2', '', true, true) ?>
<?php else: ?>
<?php echo $this->getChildHtml('product_options_wrapper') ?>
<?php endif; ?>
			</div>

			<div class="pdpbutton-wrapp addtobag">
						<?php $buttonTitle = $this->__('SHOP NOW'); ?>
							<button id="cart-add-to-bag" type="button" title="<?php echo $buttonTitle ?>" class="ShopNowButton add_to_cart addtobag-btn gtm-track" onclick="javascript:ValidateIcart(this,<?php echo $_product->getId() ?>,'<?php echo addslashes($_product->getName()) ?>'); return false;"><span>ADD TO BAG +</span></button>
					</div>
					
					<div id="error-add-to-cart" class="msg-error"></div>

			<div class="itemAddtobeg">
				<?php if (!$this->hasOptions()): ?>
					<div class="add-to-box">
						<?php if ($_product->isSaleable()): ?>
							<?php echo $this->getChildHtml('addtocart') ?>
						<?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
					</div>
				<?php else: ?>
					<?php if ($_product->isSaleable()): ?>
						<div class="options-container-small">
							<?php echo $this->getChildChildHtml('container1', '', true, true) ?>
						</div>
					<?php endif; ?>
				<?php endif; ?>
			</div>        
            
            <!--<div class="viewpdp-link-w"><a href="<?php //echo $_product->getProductUrl(); ?>">View full product details</a></div>-->
    </div>
    	
    	<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('quick-static-content')->toHtml(); ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
            <input type="hidden" name="is_input_file" id="is_input_file" value="0" />
            <input type="hidden" name="referer_url" value="<?php echo $this->getRequest()->getServer('HTTP_REFERER') ?>" />
        </div>
        </div>
    </form>

<script type="text/javascript">
	
	jQuery('.quickslide .bxslider').bxSlider({
				auto: false,
				infiniteLoop: false,
				controls: true,
				mode: 'vertical',
				touchEnabled: true,
				minSlides: 5,
				maxSlides: 6,
				slideMargin: 6,
				pager: false
			  });

	
jQuery('.quickslide img').click(function(){
	var dataLarge = jQuery(this).attr('data-larger');
	jQuery('.quickleft .mainimage img').attr('src',dataLarge);
	jQuery(this).parent().siblings().find('.active').removeClass('active');
	jQuery(this).addClass('active');
	});
</script>
</div>
</div>
<script type="text/javascript">
    //<![CDATA[
        var productAddToCartFormIcart = new VarienForm('product_addtocart_form_icart');
        if ($$('input[type="file"]').length==0) {
            productAddToCartFormIcart.submit = function(){
                    if (this.validator.validate()) {
							//updateShortlists(<?php //echo $_product->getId() ?>,'<?php //echo addslashes($_product->getName()) ?>');
                            iCart.submitForm(this.form, 'post');
                }
            }.bind(productAddToCartFormIcart);
         } else {
            $('is_input_file').value = 1;
         }
		
		function ValidateIcart(obj,id,name){
			var sizeicart = jQuery("#icart-product-view #"+id+"_size_attribute_id");
			var coloricart = jQuery("#icart-product-view #"+id+"_color_attribute_id");
			
			if(sizeicart.val() == "" || coloricart.val() == ""){
				//jQuery("#error-add-to-cart").fadeIn("slow");
				//jQuery("#error-add-to-cart").text( 'Uh-oh! Please select the Size of the Product you want to Add to Bag.');
				//setTimeout(function() { jQuery('#error-add-to-cart').hide();}, 5000);
				jQuery("#cart-add-to-bag").hide();
				jQuery('.size-info-close').show();
				jQuery('.ajax-color-swatch').addClass('color-swatch-active');
				jQuery('.validatesize').show();
				jQuery('.size-info-close').addClass('size-close-btn');	
				jQuery('.size-info-close').show();			
			}else{
				productAddToCartFormIcart.submit(obj);
			}
		}
		
    //]]>
    </script>
    <script type="text/javascript">
	jQuery('.size-info-close').click(function(){
		jQuery(this).hide();
		jQuery('.ajax-color-swatch').removeClass('color-swatch-active');
		jQuery('#cart-add-to-bag').css({ display: "block" });
		jQuery('.info-dialog').removeClass('info-dialog-active');
		jQuery('.size-info-close').hide();
	});			
</script>