<div style="text-align: center;">
<?php $requestUrl=$this->getRequest()->getRequestString();
echo $this->getMessagesBlock()->getGroupedHtml();
?>
</div>
<script type="text/javascript">
//<![CDATA[
iCart.autoClose(<?php echo (int) Mage::getStoreConfig('mageworx_customers/icart/auto_hide') ?>);
<?php if (strpos($requestUrl, '/addToWishlist/')) { ?>    
    // wishlist    
<?php } elseif (strpos($requestUrl, '/addToCompare/')) {?>
    // compare
    iCart.replaceBlock($$('div.block-compare', 'div.mini-compare'), <?php echo Zend_Json::encode($this->getChildHtml('catalog.compare.sidebar'))?>);
<?php } else {?>
    // cart            
    iCart.updateBlock($$('.cartHeader'), <?php echo Zend_Json::encode($this->getTopLinkCart())?>);
    <?php if (preg_match('~/checkout/cart/~', $this->getRequest()->getServer('HTTP_REFERER'))): ?>
        iCart.updateBlock($$('div.cart'), <?php echo Zend_Json::encode($this->getChildHtml('checkout.cart'))?>);
    <?php endif ?>
    iCart.replaceBlock($$('div.top-cart'), <?php echo Zend_Json::encode($this->getChildHtml('cart_sidebar_icart'))?>);            
<?php } ?>
jQuery('#topCartContent .close-btn').click(function() {
	jQuery("#topCartContent").slideUp(400);
});
jQuery('#cartHeader').click(function() {
	jQuery('#topCartContent').slideToggle('slow', function() {
    // Animation complete.
	});
});
iCart.updateLinks();
var qty = "<?php echo (int)Mage::getModel('checkout/cart')->getQuote()->getItemsQty(); ?>"+' '+'Items';
jQuery('.bagsummary p').html(qty);
if(jQuery('#quickbag').css('display') == 'block'){
    var bagslider = jQuery('#quickbag .productslide .bxslider').bxSlider({
                auto: true,
                infiniteLoop: true,
                mode: 'horizontal',
                slideWidth: 150,
                minSlides: 2,
                maxSlides:6,
                slideMargin: 3,
                pager: false
            });
        bagslider.reloadSlider();
}
else{
    jQuery('#showbag, #closebag').bind('click',function(){
    var bagslider = jQuery('#quickbag .productslide .bxslider').bxSlider({
                auto: true,
                infiniteLoop: true,
                mode: 'horizontal',
                slideWidth: 150,
                minSlides: 2,
                maxSlides:6,
                slideMargin: 3,
                pager: false
            });
    setTimeout(function() {
        bagslider.reloadSlider();
    }, 100);
});    
}


// update my bag

//]]>
</script>
