<?php
$controller = $this->getRequest()->getControllerName();
$action = $this->getRequest()->getActionName();
$module = $this->getRequest()->getModuleName();
$var = '';

if(isset($_GET['sale'])){
    $var = $_GET['sale'];
}

$catId = '';
/*echo '<!-- ';
echo $controller . "\n";
echo $action . "\n";
echo $module . "\n";
echo $_GET['catId'] . "\n";
echo $_GET['sale'] . "\n";
print_r( $crumbs );
echo ' -->';*/
if( isset( $_GET['catId'] ) ) {
    $category = Mage::getModel("catalog/category")->load($_GET['catId']);
    $lastCrumbName = '';
    if(isset($_GET['name'])) { $lastCrumbName = $_GET['name']; }
    if($category) {
        if($path = $category->getUrlKey()) {
            $path = explode('/', $path);
            $crumbs = array('home' => array('label' => 'Home', 'title' => 'Home', 'link' => Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB), 'first' => true, 'last' => false ));
            $crumbs['category'] = array('label' =>  $category->getName(), 'title' => $category->getName(), 'link' => $category->getUrl(), 'first' => false, 'last' => false );
            $crumbs['current'] = array('label' => $lastCrumbName, 'title' => '', 'link' => '', 'first' => false, 'last' => true );
        }
    }
}

$word = Mage::helper('catalogsearch')->getEscapedQueryText();
if($word == '439ed537979d8e831561964dbbbd7413') {
    if(isset($_SESSION['salecrumbs'])) {
        unset($_SESSION['salecrumbs']);
    }
    $_SESSION['salecrumbs'] = $crumbs;
}
?>
<?php
if(isset($_SESSION['salecrumbs']) && $var == 'true'){ ?>
    <div class="breadcrumb">
        <ul class="clearfix">
            <?php   if($_SESSION['salecrumbs'] && is_array($_SESSION['salecrumbs'])) { ?>
            <?php
                foreach($_SESSION['salecrumbs'] as $_crumbName=>$_crumbInfo){
                    $crumbsnew[$_crumbName] = $_crumbInfo;
                }
                $crumbsnew[]=$crumbs['product'];
                    foreach($crumbsnew as $_crumbName=>$_crumbInfo) { ?>
                <?php   $_crumbInfo['label'] = ucfirst(strtolower($_crumbInfo['label'])); ?>
                        <li>
                            <?php if($_crumbInfo['link']): ?>
                            <a href="<?php echo Mage::getBaseUrl().'catalogsearch/result/'.$_crumbInfo['link']; ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></a>
                            <?php else: ?>
                                <?php echo $this->htmlEscape($_crumbInfo['label']); ?>
                            <?php endif; ?>
                        </li>
                        <?php if($_crumbName != 'product') { ?>
                            <li class="brsep"></li>
                        <?php } // end if last
                    } //end for foreach loop
            } ?>
        </ul>
    </div>
<?php
} else {
    if($controller == 'customer' && $module == 'rewardsref' && $action == 'index') {
?>
<div class="breadcrumb">
    <ul class="clearfix">
        <li>
            <a title="Home Page" href="<?php echo $this->getBaseUrl(); ?>">
            Home
            </a>
        </li>

        <li class="brsep"></li>
        <li>
            <a title="My Account" href="<?php echo $this->getBaseUrl().'customer/account/'; ?>">
            My Account
            </a>
        </li>

        <li class="brsep"></li>
        <li>
        Referral
        Program
        </li>

   </ul>
</div>
<?php
} else {
    if($crumbs && is_array($crumbs)) {
?>
<div class="breadcrumb">
    <ul class="clearfix">
        <?php
        foreach($crumbs as $_crumbName=>$_crumbInfo) {
        if($controller=='account' && $action=='create' && $module=='customer') {
            if($this->htmlEscape(trim($_crumbInfo['label'] == 'Create an Account'))) {
                $_crumbInfo['label'] = 'Register / Create account';
            }
        }
        ?>
        <?php   $_crumbInfo['label'] = ucfirst(strtolower($_crumbInfo['label'])); ?>
        <li <?php if($_crumbInfo['last']){ echo 'class="last-child"'; }  ?>>
            <?php if($_crumbInfo['link']): ?>
            <a href="<?php echo (strtolower($_crumbInfo['label']) == 'sale' ? 'javascript:void(0);' : $_crumbInfo['link']) ?>" title="<?php echo $this->htmlEscape( $_crumbInfo['title'] ) ?>"><?php echo ucwords(strtolower($this->htmlEscape($_crumbInfo['label']))) ?></a>
            <?php elseif($_crumbInfo['last']):  ?>
                <?php $temp = explode(':',$_crumbInfo['label']);
                if(isset($temp[1]) && trim($temp[1]) == "'439ed537979d8e831561964dbbbd7413'"): ?>
                <?php else: ?>
                <?php echo ucwords(strtolower($this->htmlEscape($_crumbInfo['label']))); ?>
                <?php endif; ?>
            <?php else: ?>
                <?php echo ucwords(strtolower($this->htmlEscape($_crumbInfo['label']))); ?>
            <?php endif; ?>
        </li>
        <?php if(!$_crumbInfo['last']) { ?>
            <li class="brsep"></li>
        <?php }
        } ?>
    </ul>
</div>
<?php
    } // end of main if
} // end of else
}
?>