<div class="mb10 pt5"></div>
<div class="as-info-cont">
<header class="pos-a">
<div class=" cust-call pos-r fr">
<div class="fl f-Proxnova c-fff pl30"><span class="call-icon pos-a"></span> <?php echo Mage::getStoreConfig('general/store_information/phone');     ?>
</div>
</header>
</div>
<div class="chk-top-hwrap">
   <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="fl">
		<img src="<?php echo $this->getSkinurl() ?>images-v3/chk-ams-logo.jpg" alt="<?php echo $this->getLogoAlt() ?>" />
	</a>
   <div class="chk-tp-r fr">
	   <div style="width:190px" class="safe-seq fs12 c-pantone tt-u pt15 fl mt5">
       <span class="fl safe-ico"></span>       Safe and Secure<br> Shopping Guarantee
      </div>
	   <span class="chk-free-ship fl" style="width: 115px;">&nbsp;</span>
	   <span class="chk-cod-icon fl" style="width: 115px;">&nbsp;</span>
	   <span class="chk-rday-pol">&nbsp;</span>
   </div>
</div>
