<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<table width="100%" cellpadding="5" cellspacing="0" border="0" class="listOrders f-lato fs14">
    <tr>
        <td>
            <form method="post" action="<?php echo $this->getUrl('customer/account/editPost') ?>" id="form-validate" enctype="multipart/form-data">
                <?php echo $this->getBlockHtml('formkey') ?>
                <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('customer/account/navigation.phtml')->toHtml(); ?>
                <table style="float: left; width: 700px;" width="100%" cellpadding="5" cellspacing="5" border="0" class="address f-lato fs16 ml40 acc-perdetail">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->setTemplate('customer/widget/personalinfoedit.phtml')->toHtml() ?>
                    <tr>
                        <td>
                            <label for="mobile" class="required">Mobile<span class="mandatoryField">*</span></label>
                            <input type="text" name="telephone" id="mobile" value="<?php echo $this->htmlEscape($this->getCustomer()->getTelephone()) ?>" title="<?php echo $this->__('Mobile') ?>" class="input-text validate-mobile required-entry textfield" />

                        </td>
                    </tr>
                    <!--OW start-->
                    <tr>
                    <td>
                        <label for="gender"><a name="scroll-to-bottom">Gender</a></label>
                    <?php $gender=$this->htmlEscape($this->getCustomer()->getGender());?>
                    <select title="Gender" name="gender" id="gender" class="acc-city">
                     <option value="">Select Gender</option>
                    <option <?php if ($gender == 1 ) echo 'selected'; ?> value="1">Male</option>
                    <option <?php if ($gender == 2 ) echo 'selected'; ?> value="2">Female</option>
                    </select></div>
                    
                    </td>
                    </tr>
						<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob');?>
                        <?php if ($_dob->isEnabled()): ?>
                        <?php echo $_dob->setDate($this->getCustomer()->getDob())->setTemplate('customer/widget/dobedit.phtml')->toHtml() ?>
                        <?php endif ?>
                    <?php $_spousedob = $this->getLayout()->createBlock('customer/widget_spousedob');?>
                        <?php if ($_spousedob->isEnabled()): ?>
                        <?php echo $_spousedob->setDate($this->getCustomer()->getSpouseDob())->setTemplate('customer/widget/spousedobedit.phtml')->toHtml() ?>
                        <?php endif ?>
                    <tr>
                        <td>
                            <label for="city" class="required"><?php echo $this->__('City') ?></label>
                            <input type="text" name="city" id="city" value="<?php echo $this->htmlEscape($this->getCustomer()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text textfield" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="relationship" class="required"><?php echo $this->__('Relationship') ?></label>
                            <input type="text" name="relationship" id="city" value="<?php echo $this->htmlEscape($this->getCustomer()->getRelationship()) ?>" title="<?php echo $this->__('Relationship') ?>" class="input-text textfield" />
                        </td>
                    </tr>
                    <?php if ($this->getLayout()->getBlockSingleton('customer/form_register')->isNewsletterEnabled()): ?>
                                    <tr>
                                        <td>
        <label for="newsletter"  class="billship fr " style="width:380px; margin-left:149px;">
                                            <input type="checkbox" name="is_subscribed" style="display: block !important;" id="subscription" value="1" title="<?php echo $this->__('Newsletter Subscription') ?>"<?php if ($this->getSubscriptionObject()->isSubscribed()): ?> checked="checked"<?php endif; ?> class="styled fl checkbox " />
                                          <span class="mt5 ml5 fl">Subscribe for American Swan Newsletters</span></label></td>
                                        </tr>
                    <?php endif; ?>
                                        <tr>
                                            <td class="updatepwd" style="display:none;"><br />
                                                <input type="checkbox" style="display:none;" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if ($this->getCustomer()->getChangePassword() == 1): ?> checked="checked"<?php endif; ?> class="checkbox" />
                                                    <div class="updatePass">
                                                        <table width="100%" cellpadding="5" cellspacing="5" border="0" class="address">
                                                            <tr>
                                                                <td>
                                                                    <label for="email" class="required"><?php echo $this->__('Email') ?><span class="mandatoryField">*</span></label>
                                                                    &nbsp; <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>
                                                                    <input readonly="true" type="hidden" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email textfield" />
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>
                                                                    <label for="current_password" class="fl"><?php echo $this->__('Old Password') ?><span class="mandatoryField">*</span></label>
                                                                    <input type="password" class="input-text textfield fl" name="current_password" id="current_password" />
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>
                                                                    <label for="password">New Password<span class="mandatoryField">*</span></label>
                                                                    <input type="password" class="input-text validate-password textfield" name="password" id="password" />
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>
                                                                    <label for="confirmation"><?php echo $this->__('Repeat New Password') ?><span class="mandatoryField">*</span></label>
                                                                    <input type="password" class="input-text validate-cpassword textfield" name="confirmation" id="confirmation" />
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr><td><button id="registerEditId" class="btnsubmit btnupdate" name="" type="submit">SAVE CHANGES</button></td></tr>
                                        </table>

                                        <script type="text/javascript">
                                            //<![CDATA[
                                            var dataForm = new VarienForm('form-validate', true);
                                            function setPasswordForm(arg){
                                                if(arg){
                                                    jQuery('.updatepwd').show();
                                                    $('current_password').addClassName('required-entry');
                                                    $('password').addClassName('required-entry');
                                                    $('confirmation').addClassName('required-entry');
                                                    location.href="#scroll-to-bottom";
                                                }else{
                                                    jQuery('.updatepwd').hide();
                                                    $('current_password').removeClassName('required-entry');
                                                    $('password').removeClassName('required-entry');
                                                    $('confirmation').removeClassName('required-entry');
                                                }
                                            }
                                            if (window.location.hash == '#scroll-to-bottom') {
                                                setPasswordForm(true);
                                            }
                                            <?php if ($this->getCustomer()->getChangePassword()): ?>
                                                setPasswordForm(true);
                                            <?php endif; ?>
                                            //]]>
                                       </script>
									   
								<script type="text/javascript">
								
								<?php if ($_dob->isRequired()): ?>
								
								jQuery('#registerEditId').click(function() {
									var reg_day = jQuery('#day').val();
									var reg_month = jQuery('#month').val();
									var reg_year = jQuery('#year').val();

									if (!reg_day || !reg_month || !reg_year) {			
										if(!jQuery('#date-advice').val()) {
											jQuery('#date-advice').html('Uh-oh! Please enter a valid full date.');			
											jQuery('#date-advice').show();
											return false;
										}
									}
								});
								
								jQuery('#day, #month, #year').change(function() {
									var reg_day = jQuery('#day').val();
									var reg_month = jQuery('#month').val();
									var reg_year = jQuery('#year').val();

									if (reg_day && reg_month && reg_year) {			
											jQuery('#date-advice').hide();
											return true;
										}
									
								});
								
								<?php endif; ?>
								
								</script>
          </form>
        </td>
    </tr>
</table>